// This file is automatically generated.
// Do not modify this file manually.


#ifdef SWIGCHICKEN
%module itkValuedRegionalMinimaImageFilterChicken
#endif
#ifdef SWIGCSHARP
%module itkValuedRegionalMinimaImageFilterCsharp
#endif
#ifdef SWIGGUILE
%module itkValuedRegionalMinimaImageFilterGuile
#endif
#ifdef SWIGJAVA
%module itkValuedRegionalMinimaImageFilterJava
#endif
#ifdef SWIGLUA
%module itkValuedRegionalMinimaImageFilterLua
#endif
#ifdef SWIGMODULA3
%module itkValuedRegionalMinimaImageFilterModula3
#endif
#ifdef SWIGMZSCHEME
%module itkValuedRegionalMinimaImageFilterMzscheme
#endif
#ifdef SWIGOCAML
%module itkValuedRegionalMinimaImageFilterOcaml
#endif
#ifdef SWIGPERL
%module itkValuedRegionalMinimaImageFilterPerl
#endif
#ifdef SWIGPERL5
%module itkValuedRegionalMinimaImageFilterPerl5
#endif
#ifdef SWIGPHP
%module itkValuedRegionalMinimaImageFilterPhp
#endif
#ifdef SWIGPHP4
%module itkValuedRegionalMinimaImageFilterPhp4
#endif
#ifdef SWIGPHP5
%module itkValuedRegionalMinimaImageFilterPhp5
#endif
#ifdef SWIGPIKE
%module itkValuedRegionalMinimaImageFilterPike
#endif
#ifdef SWIGPYTHON
%module itkValuedRegionalMinimaImageFilterPython
#endif
#ifdef SWIGR
%module itkValuedRegionalMinimaImageFilterR
#endif
#ifdef SWIGRUBY
%module itkValuedRegionalMinimaImageFilterRuby
#endif
#ifdef SWIGSEXP
%module itkValuedRegionalMinimaImageFilterSexp
#endif
#ifdef SWIGTCL
%module itkValuedRegionalMinimaImageFilterTcl
#endif
#ifdef SWIGXML
%module itkValuedRegionalMinimaImageFilterXml
#endif

%{
#include "VXLNumerics.includes"
#include "Base.includes"
#include "Review.includes"
%}


%{
%}




%import wrap_ITKCommonBase.i
%import wrap_itkImageToImageFilterA.i


%include itk.i
%include wrap_itkValuedRegionalMinimaImageFilter_ext.i


 class itkValuedRegionalMinimaImageFilterID2ID2_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterID2ID2_Pointer();
     itkValuedRegionalMinimaImageFilterID2ID2_Pointer(itkValuedRegionalMinimaImageFilterID2ID2_Pointer const & p);
     itkValuedRegionalMinimaImageFilterID2ID2_Pointer(itkValuedRegionalMinimaImageFilterID2ID2 * p);
     ~itkValuedRegionalMinimaImageFilterID2ID2_Pointer();
     itkValuedRegionalMinimaImageFilterID2ID2 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterID2ID2 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterID2ID2_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterID2ID2_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterID2ID2_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterID2ID2_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterID2ID2_Pointer & operator=(itkValuedRegionalMinimaImageFilterID2ID2_Pointer const & r);
     itkValuedRegionalMinimaImageFilterID2ID2_Pointer & operator=(itkValuedRegionalMinimaImageFilterID2ID2 * r);
     itkValuedRegionalMinimaImageFilterID2ID2 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterID2ID2_Superclass : public itkImageToImageFilterID2ID2 {
   public:
     enum  {  InputImageDimension = 2 };
     enum  {  OutputImageDimension = 2 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(double const _arg);
     virtual double const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass(itkValuedRegionalMinimaImageFilterID2ID2_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterID2ID2_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass();
     ~itkValuedRegionalMinimaImageFilterID2ID2_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterID2ID2_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterID2ID2_Superclass * r);
     itkValuedRegionalMinimaImageFilterID2ID2_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterID3ID3_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterID3ID3_Pointer();
     itkValuedRegionalMinimaImageFilterID3ID3_Pointer(itkValuedRegionalMinimaImageFilterID3ID3_Pointer const & p);
     itkValuedRegionalMinimaImageFilterID3ID3_Pointer(itkValuedRegionalMinimaImageFilterID3ID3 * p);
     ~itkValuedRegionalMinimaImageFilterID3ID3_Pointer();
     itkValuedRegionalMinimaImageFilterID3ID3 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterID3ID3 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterID3ID3_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterID3ID3_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterID3ID3_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterID3ID3_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterID3ID3_Pointer & operator=(itkValuedRegionalMinimaImageFilterID3ID3_Pointer const & r);
     itkValuedRegionalMinimaImageFilterID3ID3_Pointer & operator=(itkValuedRegionalMinimaImageFilterID3ID3 * r);
     itkValuedRegionalMinimaImageFilterID3ID3 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterID3ID3_Superclass : public itkImageToImageFilterID3ID3 {
   public:
     enum  {  InputImageDimension = 3 };
     enum  {  OutputImageDimension = 3 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(double const _arg);
     virtual double const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass(itkValuedRegionalMinimaImageFilterID3ID3_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterID3ID3_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass();
     ~itkValuedRegionalMinimaImageFilterID3ID3_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterID3ID3_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterID3ID3_Superclass * r);
     itkValuedRegionalMinimaImageFilterID3ID3_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIF2IF2_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIF2IF2_Pointer();
     itkValuedRegionalMinimaImageFilterIF2IF2_Pointer(itkValuedRegionalMinimaImageFilterIF2IF2_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIF2IF2_Pointer(itkValuedRegionalMinimaImageFilterIF2IF2 * p);
     ~itkValuedRegionalMinimaImageFilterIF2IF2_Pointer();
     itkValuedRegionalMinimaImageFilterIF2IF2 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIF2IF2 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIF2IF2_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIF2IF2_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIF2IF2_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIF2IF2_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIF2IF2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF2IF2_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIF2IF2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF2IF2 * r);
     itkValuedRegionalMinimaImageFilterIF2IF2 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIF2IF2_Superclass : public itkImageToImageFilterIF2IF2 {
   public:
     enum  {  InputImageDimension = 2 };
     enum  {  OutputImageDimension = 2 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(float const _arg);
     virtual float const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass();
     ~itkValuedRegionalMinimaImageFilterIF2IF2_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF2IF2_Superclass * r);
     itkValuedRegionalMinimaImageFilterIF2IF2_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIF3IF3_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIF3IF3_Pointer();
     itkValuedRegionalMinimaImageFilterIF3IF3_Pointer(itkValuedRegionalMinimaImageFilterIF3IF3_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIF3IF3_Pointer(itkValuedRegionalMinimaImageFilterIF3IF3 * p);
     ~itkValuedRegionalMinimaImageFilterIF3IF3_Pointer();
     itkValuedRegionalMinimaImageFilterIF3IF3 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIF3IF3 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIF3IF3_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIF3IF3_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIF3IF3_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIF3IF3_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIF3IF3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF3IF3_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIF3IF3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF3IF3 * r);
     itkValuedRegionalMinimaImageFilterIF3IF3 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIF3IF3_Superclass : public itkImageToImageFilterIF3IF3 {
   public:
     enum  {  InputImageDimension = 3 };
     enum  {  OutputImageDimension = 3 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(float const _arg);
     virtual float const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass();
     ~itkValuedRegionalMinimaImageFilterIF3IF3_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIF3IF3_Superclass * r);
     itkValuedRegionalMinimaImageFilterIF3IF3_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer();
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer(itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer(itkValuedRegionalMinimaImageFilterIUC2IUC2 * p);
     ~itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer();
     itkValuedRegionalMinimaImageFilterIUC2IUC2 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUC2IUC2 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC2IUC2 * r);
     itkValuedRegionalMinimaImageFilterIUC2IUC2 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass : public itkImageToImageFilterIUC2IUC2 {
   public:
     enum  {  InputImageDimension = 2 };
     enum  {  OutputImageDimension = 2 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(unsigned char const _arg);
     virtual unsigned char const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass();
     ~itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass * r);
     itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer();
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer(itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer(itkValuedRegionalMinimaImageFilterIUC3IUC3 * p);
     ~itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer();
     itkValuedRegionalMinimaImageFilterIUC3IUC3 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUC3IUC3 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC3IUC3 * r);
     itkValuedRegionalMinimaImageFilterIUC3IUC3 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass : public itkImageToImageFilterIUC3IUC3 {
   public:
     enum  {  InputImageDimension = 3 };
     enum  {  OutputImageDimension = 3 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(unsigned char const _arg);
     virtual unsigned char const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass();
     ~itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass * r);
     itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer();
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer(itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer(itkValuedRegionalMinimaImageFilterIUL2IUL2 * p);
     ~itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer();
     itkValuedRegionalMinimaImageFilterIUL2IUL2 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUL2IUL2 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL2IUL2 * r);
     itkValuedRegionalMinimaImageFilterIUL2IUL2 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass : public itkImageToImageFilterIUL2IUL2 {
   public:
     enum  {  InputImageDimension = 2 };
     enum  {  OutputImageDimension = 2 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(unsigned long const _arg);
     virtual unsigned long const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass();
     ~itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass * r);
     itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer();
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer(itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer(itkValuedRegionalMinimaImageFilterIUL3IUL3 * p);
     ~itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer();
     itkValuedRegionalMinimaImageFilterIUL3IUL3 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUL3IUL3 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL3IUL3 * r);
     itkValuedRegionalMinimaImageFilterIUL3IUL3 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass : public itkImageToImageFilterIUL3IUL3 {
   public:
     enum  {  InputImageDimension = 3 };
     enum  {  OutputImageDimension = 3 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(unsigned long const _arg);
     virtual unsigned long const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass();
     ~itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass * r);
     itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer();
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer(itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer(itkValuedRegionalMinimaImageFilterIUS2IUS2 * p);
     ~itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer();
     itkValuedRegionalMinimaImageFilterIUS2IUS2 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUS2IUS2 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS2IUS2 * r);
     itkValuedRegionalMinimaImageFilterIUS2IUS2 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass : public itkImageToImageFilterIUS2IUS2 {
   public:
     enum  {  InputImageDimension = 2 };
     enum  {  OutputImageDimension = 2 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(unsigned short const _arg);
     virtual unsigned short const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass();
     ~itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass * r);
     itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer();
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer(itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer(itkValuedRegionalMinimaImageFilterIUS3IUS3 * p);
     ~itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer();
     itkValuedRegionalMinimaImageFilterIUS3IUS3 * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUS3IUS3 * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS3IUS3 * r);
     itkValuedRegionalMinimaImageFilterIUS3IUS3 * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass : public itkImageToImageFilterIUS3IUS3 {
   public:
     enum  {  InputImageDimension = 3 };
     enum  {  OutputImageDimension = 3 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
     virtual void SetFullyConnected(bool const _arg);
     virtual bool const & GetFullyConnected() const;
     virtual void FullyConnectedOn();
     virtual void FullyConnectedOff();
     virtual void SetMarkerValue(unsigned short const _arg);
     virtual unsigned short const & GetMarkerValue() const;
     virtual bool GetFlat() const;
   private:
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass();
     ~itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass();
     virtual void PrintSelf(std::basic_ostream< char, std::char_traits< char > > & os, itkIndent indent) const;
     virtual void GenerateInputRequestedRegion();
     virtual void EnlargeOutputRequestedRegion(itkDataObject * arg0);
     virtual void GenerateData();
 };


 class itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer {
   public:
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer const & p);
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass * p);
     ~itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer();
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass * operator->() const;
     bool IsNotNull() const;
     bool IsNull() const;
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass * GetPointer() const;
     bool operator<(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer const & r) const;
     bool operator>(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer const & r) const;
     bool operator<=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer const & r) const;
     bool operator>=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer const & r) const;
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer const & r);
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass_Pointer & operator=(itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass * r);
     itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass * Print(std::basic_ostream< char, std::char_traits< char > > & os) const;
   private:
     void Register();
     void UnRegister();
   protected:
 };


 class itkValuedRegionalMinimaImageFilterID2ID2 : public itkValuedRegionalMinimaImageFilterID2ID2_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterID2ID2_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterID2ID2(itkValuedRegionalMinimaImageFilterID2ID2 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterID2ID2 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterID2ID2();
     ~itkValuedRegionalMinimaImageFilterID2ID2();
 };


 class itkValuedRegionalMinimaImageFilterID3ID3 : public itkValuedRegionalMinimaImageFilterID3ID3_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterID3ID3_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterID3ID3(itkValuedRegionalMinimaImageFilterID3ID3 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterID3ID3 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterID3ID3();
     ~itkValuedRegionalMinimaImageFilterID3ID3();
 };


 class itkValuedRegionalMinimaImageFilterIF2IF2 : public itkValuedRegionalMinimaImageFilterIF2IF2_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIF2IF2_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIF2IF2(itkValuedRegionalMinimaImageFilterIF2IF2 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIF2IF2 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIF2IF2();
     ~itkValuedRegionalMinimaImageFilterIF2IF2();
 };


 class itkValuedRegionalMinimaImageFilterIF3IF3 : public itkValuedRegionalMinimaImageFilterIF3IF3_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIF3IF3_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIF3IF3(itkValuedRegionalMinimaImageFilterIF3IF3 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIF3IF3 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIF3IF3();
     ~itkValuedRegionalMinimaImageFilterIF3IF3();
 };


 class itkValuedRegionalMinimaImageFilterIUC2IUC2 : public itkValuedRegionalMinimaImageFilterIUC2IUC2_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUC2IUC2_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIUC2IUC2(itkValuedRegionalMinimaImageFilterIUC2IUC2 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUC2IUC2 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUC2IUC2();
     ~itkValuedRegionalMinimaImageFilterIUC2IUC2();
 };


 class itkValuedRegionalMinimaImageFilterIUC3IUC3 : public itkValuedRegionalMinimaImageFilterIUC3IUC3_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUC3IUC3_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIUC3IUC3(itkValuedRegionalMinimaImageFilterIUC3IUC3 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUC3IUC3 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUC3IUC3();
     ~itkValuedRegionalMinimaImageFilterIUC3IUC3();
 };


 class itkValuedRegionalMinimaImageFilterIUL2IUL2 : public itkValuedRegionalMinimaImageFilterIUL2IUL2_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUL2IUL2_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIUL2IUL2(itkValuedRegionalMinimaImageFilterIUL2IUL2 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUL2IUL2 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUL2IUL2();
     ~itkValuedRegionalMinimaImageFilterIUL2IUL2();
 };


 class itkValuedRegionalMinimaImageFilterIUL3IUL3 : public itkValuedRegionalMinimaImageFilterIUL3IUL3_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUL3IUL3_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIUL3IUL3(itkValuedRegionalMinimaImageFilterIUL3IUL3 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUL3IUL3 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUL3IUL3();
     ~itkValuedRegionalMinimaImageFilterIUL3IUL3();
 };


 class itkValuedRegionalMinimaImageFilterIUS2IUS2 : public itkValuedRegionalMinimaImageFilterIUS2IUS2_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUS2IUS2_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIUS2IUS2(itkValuedRegionalMinimaImageFilterIUS2IUS2 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUS2IUS2 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUS2IUS2();
     ~itkValuedRegionalMinimaImageFilterIUS2IUS2();
 };


 class itkValuedRegionalMinimaImageFilterIUS3IUS3 : public itkValuedRegionalMinimaImageFilterIUS3IUS3_Superclass {
   public:
     enum  {  InputPixelTypeComparable = 1 };
     enum  {  InputHasPixelTraitsCheck = 1 };
     enum  {  InputHasNumericTraitsCheck = 1 };
     static itkValuedRegionalMinimaImageFilterIUS3IUS3_Pointer New();
     virtual itkLightObject_Pointer CreateAnother() const;
     virtual char const * GetNameOfClass() const;
   private:
     itkValuedRegionalMinimaImageFilterIUS3IUS3(itkValuedRegionalMinimaImageFilterIUS3IUS3 const & arg0);
     void operator=(itkValuedRegionalMinimaImageFilterIUS3IUS3 const & arg0);
   protected:
     itkValuedRegionalMinimaImageFilterIUS3IUS3();
     ~itkValuedRegionalMinimaImageFilterIUS3IUS3();
 };


