depends = ('ITKPyBase', 'Numerics', 'Transforms', 'Base', 'VXLNumerics', )
templates = (
  ('LabelObjectLine', 'itk::LabelObjectLine', 'itkLabelObjectLine2', '2'),
  ('LabelObjectLine', 'itk::LabelObjectLine', 'itkLabelObjectLine3', '3'),
  ('LabelObject', 'itk::LabelObject', 'itkLabelObjectUL2', 'unsigned long,2'),
  ('LabelObject', 'itk::LabelObject', 'itkLabelObjectUL3', 'unsigned long,3'),
  ('ShapeLabelObject', 'itk::ShapeLabelObject', 'itkShapeLabelObjectUL2', 'unsigned long,2'),
  ('ShapeLabelObject', 'itk::ShapeLabelObject', 'itkShapeLabelObjectUL3', 'unsigned long,3'),
  ('StatisticsLabelObject', 'itk::StatisticsLabelObject', 'itkStatisticsLabelObjectUL2', 'unsigned long,2'),
  ('map', 'std::map', 'mapitkStatisticsLabelObjectUL2', 'unsigned long, itk::StatisticsLabelObject< unsigned long,2  >'),
  ('vector', 'std::vector', 'vectoritkStatisticsLabelObjectUL2', 'itk::StatisticsLabelObject< unsigned long,2  >'),
  ('StatisticsLabelObject', 'itk::StatisticsLabelObject', 'itkStatisticsLabelObjectUL3', 'unsigned long,3'),
  ('map', 'std::map', 'mapitkStatisticsLabelObjectUL3', 'unsigned long, itk::StatisticsLabelObject< unsigned long,3  >'),
  ('vector', 'std::vector', 'vectoritkStatisticsLabelObjectUL3', 'itk::StatisticsLabelObject< unsigned long,3  >'),
  ('LabelMap', 'itk::LabelMap', 'itkLabelMap2', 'itk::StatisticsLabelObject< unsigned long, 2 >'),
  ('LabelMap', 'itk::LabelMap', 'itkLabelMap3', 'itk::StatisticsLabelObject< unsigned long, 3 >'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ImageSource', 'itk::ImageSource', 'itkImageSourceLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM2LM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUC2LM2', 'itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM2IUC2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned char,2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUL2LM2', 'itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM2IUL2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned long,2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUS2LM2', 'itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM2IUS2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned short,2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIF2LM2', 'itk::Image< float,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM2IF2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< float,2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterID2LM2', 'itk::Image< double,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM2ID2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< double,2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM2IRGBUS2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM3LM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUC3LM3', 'itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM3IUC3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned char,3 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUL3LM3', 'itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM3IUL3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned long,3 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIUS3LM3', 'itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM3IUS3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned short,3 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterIF3LM3', 'itk::Image< float,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM3IF3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< float,3 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterID3LM3', 'itk::Image< double,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM3ID3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< double,3 >'),
  ('ImageToImageFilter', 'itk::ImageToImageFilter', 'itkImageToImageFilterLM3IRGBUS3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< itk::RGBPixel< unsigned short >,3 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM2LM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM2IUC2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned char,2 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM2IUL2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned long,2 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM2IUS2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned short,2 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM2IF2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< float,2 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM2ID2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< double,2 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM2IRGBUS2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM3LM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM3IUC3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned char,3 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM3IUL3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned long,3 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM3IUS3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned short,3 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM3IF3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< float,3 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM3ID3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< double,3 >'),
  ('LabelMapFilter', 'itk::LabelMapFilter', 'itkLabelMapFilterLM3IRGBUS3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< itk::RGBPixel< unsigned short >,3 >'),
  ('InPlaceLabelMapFilter', 'itk::InPlaceLabelMapFilter', 'itkInPlaceLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('InPlaceLabelMapFilter', 'itk::InPlaceLabelMapFilter', 'itkInPlaceLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ChangeRegionLabelMapFilter', 'itk::ChangeRegionLabelMapFilter', 'itkChangeRegionLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ChangeRegionLabelMapFilter', 'itk::ChangeRegionLabelMapFilter', 'itkChangeRegionLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('AggregateLabelMapFilter', 'itk::AggregateLabelMapFilter', 'itkAggregateLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('AggregateLabelMapFilter', 'itk::AggregateLabelMapFilter', 'itkAggregateLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('AutoCropLabelMapFilter', 'itk::AutoCropLabelMapFilter', 'itkAutoCropLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('AutoCropLabelMapFilter', 'itk::AutoCropLabelMapFilter', 'itkAutoCropLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIUC2IUC2SE2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIUL2IUL2SE2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIUS2IUS2SE2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIF2IF2SE2', 'itk::Image< float,2 >,itk::Image< float,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterID2ID2SE2', 'itk::Image< double,2 >,itk::Image< double,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIUC3IUC3SE3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIUL3IUL3SE3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIUS3IUS3SE3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterIF3IF3SE3', 'itk::Image< float,3 >,itk::Image< float,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryDilateImageFilter', 'itk::BinaryDilateImageFilter', 'itkBinaryDilateImageFilterID3ID3SE3', 'itk::Image< double,3 >,itk::Image< double,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIUC2IUC2SE2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIUL2IUL2SE2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIUS2IUS2SE2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIF2IF2SE2', 'itk::Image< float,2 >,itk::Image< float,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterID2ID2SE2', 'itk::Image< double,2 >,itk::Image< double,2 >,itk::FlatStructuringElement< 2 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIUC3IUC3SE3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIUL3IUL3SE3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIUS3IUS3SE3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterIF3IF3SE3', 'itk::Image< float,3 >,itk::Image< float,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryErodeImageFilter', 'itk::BinaryErodeImageFilter', 'itkBinaryErodeImageFilterID3ID3SE3', 'itk::Image< double,3 >,itk::Image< double,3 >,itk::FlatStructuringElement< 3 >'),
  ('BinaryImageToLabelMapFilter', 'itk::BinaryImageToLabelMapFilter', 'itkBinaryImageToLabelMapFilterIUC2LM2', 'itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToLabelMapFilter', 'itk::BinaryImageToLabelMapFilter', 'itkBinaryImageToLabelMapFilterIUC3LM3', 'itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToLabelMapFilter', 'itk::BinaryImageToLabelMapFilter', 'itkBinaryImageToLabelMapFilterIUL2LM2', 'itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToLabelMapFilter', 'itk::BinaryImageToLabelMapFilter', 'itkBinaryImageToLabelMapFilterIUL3LM3', 'itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToLabelMapFilter', 'itk::BinaryImageToLabelMapFilter', 'itkBinaryImageToLabelMapFilterIUS2LM2', 'itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToLabelMapFilter', 'itk::BinaryImageToLabelMapFilter', 'itkBinaryImageToLabelMapFilterIUS3LM3', 'itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToShapeLabelMapFilter', 'itk::BinaryImageToShapeLabelMapFilter', 'itkBinaryImageToShapeLabelMapFilterIUC2LM2', 'itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToShapeLabelMapFilter', 'itk::BinaryImageToShapeLabelMapFilter', 'itkBinaryImageToShapeLabelMapFilterIUC3LM3', 'itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToShapeLabelMapFilter', 'itk::BinaryImageToShapeLabelMapFilter', 'itkBinaryImageToShapeLabelMapFilterIUL2LM2', 'itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToShapeLabelMapFilter', 'itk::BinaryImageToShapeLabelMapFilter', 'itkBinaryImageToShapeLabelMapFilterIUL3LM3', 'itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToShapeLabelMapFilter', 'itk::BinaryImageToShapeLabelMapFilter', 'itkBinaryImageToShapeLabelMapFilterIUS2LM2', 'itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToShapeLabelMapFilter', 'itk::BinaryImageToShapeLabelMapFilter', 'itkBinaryImageToShapeLabelMapFilterIUS3LM3', 'itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC2IUC2LM2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC3IUC3LM3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC2IUL2LM2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC3IUL3LM3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC2IUS2LM2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC3IUS3LM3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC2IF2LM2', 'itk::Image< unsigned char,2 >, itk::Image< float,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC3IF3LM3', 'itk::Image< unsigned char,3 >, itk::Image< float,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC2ID2LM2', 'itk::Image< unsigned char,2 >, itk::Image< double,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUC3ID3LM3', 'itk::Image< unsigned char,3 >, itk::Image< double,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL2IUC2LM2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL3IUC3LM3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL2IUL2LM2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL3IUL3LM3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL2IUS2LM2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL3IUS3LM3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL2IF2LM2', 'itk::Image< unsigned long,2 >, itk::Image< float,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL3IF3LM3', 'itk::Image< unsigned long,3 >, itk::Image< float,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL2ID2LM2', 'itk::Image< unsigned long,2 >, itk::Image< double,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUL3ID3LM3', 'itk::Image< unsigned long,3 >, itk::Image< double,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS2IUC2LM2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS3IUC3LM3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS2IUL2LM2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS3IUL3LM3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS2IUS2LM2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS3IUS3LM3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS2IF2LM2', 'itk::Image< unsigned short,2 >, itk::Image< float,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS3IF3LM3', 'itk::Image< unsigned short,3 >, itk::Image< float,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS2ID2LM2', 'itk::Image< unsigned short,2 >, itk::Image< double,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('BinaryImageToStatisticsLabelMapFilter', 'itk::BinaryImageToStatisticsLabelMapFilter', 'itkBinaryImageToStatisticsLabelMapFilterIUS3ID3LM3', 'itk::Image< unsigned short,3 >, itk::Image< double,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('BinaryPruningImageFilter', 'itk::BinaryPruningImageFilter', 'itkBinaryPruningImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryPruningImageFilter', 'itk::BinaryPruningImageFilter', 'itkBinaryPruningImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryPruningImageFilter', 'itk::BinaryPruningImageFilter', 'itkBinaryPruningImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryPruningImageFilter', 'itk::BinaryPruningImageFilter', 'itkBinaryPruningImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BinaryPruningImageFilter', 'itk::BinaryPruningImageFilter', 'itkBinaryPruningImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BinaryShapeKeepNObjectsImageFilter', 'itk::BinaryShapeKeepNObjectsImageFilter', 'itkBinaryShapeKeepNObjectsImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('BinaryShapeKeepNObjectsImageFilter', 'itk::BinaryShapeKeepNObjectsImageFilter', 'itkBinaryShapeKeepNObjectsImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('BinaryShapeKeepNObjectsImageFilter', 'itk::BinaryShapeKeepNObjectsImageFilter', 'itkBinaryShapeKeepNObjectsImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('BinaryShapeKeepNObjectsImageFilter', 'itk::BinaryShapeKeepNObjectsImageFilter', 'itkBinaryShapeKeepNObjectsImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('BinaryShapeKeepNObjectsImageFilter', 'itk::BinaryShapeKeepNObjectsImageFilter', 'itkBinaryShapeKeepNObjectsImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('BinaryShapeKeepNObjectsImageFilter', 'itk::BinaryShapeKeepNObjectsImageFilter', 'itkBinaryShapeKeepNObjectsImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('BinaryShapeOpeningImageFilter', 'itk::BinaryShapeOpeningImageFilter', 'itkBinaryShapeOpeningImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('BinaryShapeOpeningImageFilter', 'itk::BinaryShapeOpeningImageFilter', 'itkBinaryShapeOpeningImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('BinaryShapeOpeningImageFilter', 'itk::BinaryShapeOpeningImageFilter', 'itkBinaryShapeOpeningImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('BinaryShapeOpeningImageFilter', 'itk::BinaryShapeOpeningImageFilter', 'itkBinaryShapeOpeningImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('BinaryShapeOpeningImageFilter', 'itk::BinaryShapeOpeningImageFilter', 'itkBinaryShapeOpeningImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('BinaryShapeOpeningImageFilter', 'itk::BinaryShapeOpeningImageFilter', 'itkBinaryShapeOpeningImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned char,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned char,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned short,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >,itk::Image< float,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >,itk::Image< float,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >,itk::Image< float,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >,itk::Image< double,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >,itk::Image< double,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >,itk::Image< double,2 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned char,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned char,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned short,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >,itk::Image< float,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >,itk::Image< float,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >,itk::Image< float,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >,itk::Image< double,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >,itk::Image< double,3 >'),
  ('BinaryStatisticsKeepNObjectsImageFilter', 'itk::BinaryStatisticsKeepNObjectsImageFilter', 'itkBinaryStatisticsKeepNObjectsImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >,itk::Image< double,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned char,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned char,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned short,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >,itk::Image< float,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >,itk::Image< float,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >,itk::Image< float,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >,itk::Image< double,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >,itk::Image< double,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >,itk::Image< double,2 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned char,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned char,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned short,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >,itk::Image< float,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >,itk::Image< float,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >,itk::Image< float,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >,itk::Image< double,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >,itk::Image< double,3 >'),
  ('BinaryStatisticsOpeningImageFilter', 'itk::BinaryStatisticsOpeningImageFilter', 'itkBinaryStatisticsOpeningImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >,itk::Image< double,3 >'),
  ('BinaryThinningImageFilter', 'itk::BinaryThinningImageFilter', 'itkBinaryThinningImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThinningImageFilter', 'itk::BinaryThinningImageFilter', 'itkBinaryThinningImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryThinningImageFilter', 'itk::BinaryThinningImageFilter', 'itkBinaryThinningImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF2IUL2', 'itk::Image< float,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF3IUL3', 'itk::Image< float,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF2IUS2', 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF3IUS3', 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF2IUC2', 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF3IUC3', 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID2IF2', 'itk::Image< double,2 >, itk::Image< float,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID3IF3', 'itk::Image< double,3 >, itk::Image< float,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID2IUL2', 'itk::Image< double,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID3IUL3', 'itk::Image< double,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID2IUS2', 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID3IUS3', 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID2IUC2', 'itk::Image< double,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID3IUC3', 'itk::Image< double,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BinaryThresholdImageFilter', 'itk::BinaryThresholdImageFilter', 'itkBinaryThresholdImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ChangeLabelLabelMapFilter', 'itk::ChangeLabelLabelMapFilter', 'itkChangeLabelLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ChangeLabelLabelMapFilter', 'itk::ChangeLabelLabelMapFilter', 'itkChangeLabelLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('CropLabelMapFilter', 'itk::CropLabelMapFilter', 'itkCropLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('CropLabelMapFilter', 'itk::CropLabelMapFilter', 'itkCropLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToLabelMapFilter', 'itk::LabelImageToLabelMapFilter', 'itkLabelImageToLabelMapFilterIUC2LM2', 'itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToLabelMapFilter', 'itk::LabelImageToLabelMapFilter', 'itkLabelImageToLabelMapFilterIUC3LM3', 'itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToLabelMapFilter', 'itk::LabelImageToLabelMapFilter', 'itkLabelImageToLabelMapFilterIUL2LM2', 'itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToLabelMapFilter', 'itk::LabelImageToLabelMapFilter', 'itkLabelImageToLabelMapFilterIUL3LM3', 'itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToLabelMapFilter', 'itk::LabelImageToLabelMapFilter', 'itkLabelImageToLabelMapFilterIUS2LM2', 'itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToLabelMapFilter', 'itk::LabelImageToLabelMapFilter', 'itkLabelImageToLabelMapFilterIUS3LM3', 'itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToShapeLabelMapFilter', 'itk::LabelImageToShapeLabelMapFilter', 'itkLabelImageToShapeLabelMapFilterIUC2LM2', 'itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToShapeLabelMapFilter', 'itk::LabelImageToShapeLabelMapFilter', 'itkLabelImageToShapeLabelMapFilterIUC3LM3', 'itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToShapeLabelMapFilter', 'itk::LabelImageToShapeLabelMapFilter', 'itkLabelImageToShapeLabelMapFilterIUL2LM2', 'itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToShapeLabelMapFilter', 'itk::LabelImageToShapeLabelMapFilter', 'itkLabelImageToShapeLabelMapFilterIUL3LM3', 'itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToShapeLabelMapFilter', 'itk::LabelImageToShapeLabelMapFilter', 'itkLabelImageToShapeLabelMapFilterIUS2LM2', 'itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToShapeLabelMapFilter', 'itk::LabelImageToShapeLabelMapFilter', 'itkLabelImageToShapeLabelMapFilterIUS3LM3', 'itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC2IUC2LM2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC3IUC3LM3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC2IUL2LM2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC3IUL3LM3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC2IUS2LM2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC3IUS3LM3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC2IF2LM2', 'itk::Image< unsigned char,2 >, itk::Image< float,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC3IF3LM3', 'itk::Image< unsigned char,3 >, itk::Image< float,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC2ID2LM2', 'itk::Image< unsigned char,2 >, itk::Image< double,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUC3ID3LM3', 'itk::Image< unsigned char,3 >, itk::Image< double,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL2IUC2LM2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL3IUC3LM3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL2IUL2LM2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL3IUL3LM3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL2IUS2LM2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL3IUS3LM3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL2IF2LM2', 'itk::Image< unsigned long,2 >, itk::Image< float,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL3IF3LM3', 'itk::Image< unsigned long,3 >, itk::Image< float,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL2ID2LM2', 'itk::Image< unsigned long,2 >, itk::Image< double,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUL3ID3LM3', 'itk::Image< unsigned long,3 >, itk::Image< double,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS2IUC2LM2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS3IUC3LM3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS2IUL2LM2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS3IUL3LM3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS2IUS2LM2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS3IUS3LM3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS2IF2LM2', 'itk::Image< unsigned short,2 >, itk::Image< float,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS3IF3LM3', 'itk::Image< unsigned short,3 >, itk::Image< float,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS2ID2LM2', 'itk::Image< unsigned short,2 >, itk::Image< double,2 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('LabelImageToStatisticsLabelMapFilter', 'itk::LabelImageToStatisticsLabelMapFilter', 'itkLabelImageToStatisticsLabelMapFilterIUS3ID3LM3', 'itk::Image< unsigned short,3 >, itk::Image< double,3 >, itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('LabelMapToBinaryImageFilter', 'itk::LabelMapToBinaryImageFilter', 'itkLabelMapToBinaryImageFilterLM2IUC2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned char,2 >'),
  ('LabelMapToBinaryImageFilter', 'itk::LabelMapToBinaryImageFilter', 'itkLabelMapToBinaryImageFilterLM3IUC3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned char,3 >'),
  ('LabelMapToBinaryImageFilter', 'itk::LabelMapToBinaryImageFilter', 'itkLabelMapToBinaryImageFilterLM2IUL2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned long,2 >'),
  ('LabelMapToBinaryImageFilter', 'itk::LabelMapToBinaryImageFilter', 'itkLabelMapToBinaryImageFilterLM3IUL3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned long,3 >'),
  ('LabelMapToBinaryImageFilter', 'itk::LabelMapToBinaryImageFilter', 'itkLabelMapToBinaryImageFilterLM2IUS2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned short,2 >'),
  ('LabelMapToBinaryImageFilter', 'itk::LabelMapToBinaryImageFilter', 'itkLabelMapToBinaryImageFilterLM3IUS3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned short,3 >'),
  ('LabelMapToLabelImageFilter', 'itk::LabelMapToLabelImageFilter', 'itkLabelMapToLabelImageFilterLM2IUC2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned char,2 >'),
  ('LabelMapToLabelImageFilter', 'itk::LabelMapToLabelImageFilter', 'itkLabelMapToLabelImageFilterLM3IUC3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned char,3 >'),
  ('LabelMapToLabelImageFilter', 'itk::LabelMapToLabelImageFilter', 'itkLabelMapToLabelImageFilterLM2IUL2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned long,2 >'),
  ('LabelMapToLabelImageFilter', 'itk::LabelMapToLabelImageFilter', 'itkLabelMapToLabelImageFilterLM3IUL3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned long,3 >'),
  ('LabelMapToLabelImageFilter', 'itk::LabelMapToLabelImageFilter', 'itkLabelMapToLabelImageFilterLM2IUS2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned short,2 >'),
  ('LabelMapToLabelImageFilter', 'itk::LabelMapToLabelImageFilter', 'itkLabelMapToLabelImageFilterLM3IUS3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned short,3 >'),
  ('LabelShapeKeepNObjectsImageFilter', 'itk::LabelShapeKeepNObjectsImageFilter', 'itkLabelShapeKeepNObjectsImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('LabelShapeKeepNObjectsImageFilter', 'itk::LabelShapeKeepNObjectsImageFilter', 'itkLabelShapeKeepNObjectsImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('LabelShapeKeepNObjectsImageFilter', 'itk::LabelShapeKeepNObjectsImageFilter', 'itkLabelShapeKeepNObjectsImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('LabelShapeKeepNObjectsImageFilter', 'itk::LabelShapeKeepNObjectsImageFilter', 'itkLabelShapeKeepNObjectsImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('LabelShapeKeepNObjectsImageFilter', 'itk::LabelShapeKeepNObjectsImageFilter', 'itkLabelShapeKeepNObjectsImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('LabelShapeKeepNObjectsImageFilter', 'itk::LabelShapeKeepNObjectsImageFilter', 'itkLabelShapeKeepNObjectsImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('LabelShapeOpeningImageFilter', 'itk::LabelShapeOpeningImageFilter', 'itkLabelShapeOpeningImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('LabelShapeOpeningImageFilter', 'itk::LabelShapeOpeningImageFilter', 'itkLabelShapeOpeningImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('LabelShapeOpeningImageFilter', 'itk::LabelShapeOpeningImageFilter', 'itkLabelShapeOpeningImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('LabelShapeOpeningImageFilter', 'itk::LabelShapeOpeningImageFilter', 'itkLabelShapeOpeningImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('LabelShapeOpeningImageFilter', 'itk::LabelShapeOpeningImageFilter', 'itkLabelShapeOpeningImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('LabelShapeOpeningImageFilter', 'itk::LabelShapeOpeningImageFilter', 'itkLabelShapeOpeningImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >,itk::Image< float,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >,itk::Image< float,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >,itk::Image< float,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >,itk::Image< double,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >,itk::Image< double,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >,itk::Image< double,2 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >,itk::Image< float,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >,itk::Image< float,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >,itk::Image< float,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >,itk::Image< double,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >,itk::Image< double,3 >'),
  ('LabelStatisticsKeepNObjectsImageFilter', 'itk::LabelStatisticsKeepNObjectsImageFilter', 'itkLabelStatisticsKeepNObjectsImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >,itk::Image< double,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >,itk::Image< float,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >,itk::Image< float,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >,itk::Image< float,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >,itk::Image< double,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >,itk::Image< double,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >,itk::Image< double,2 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >,itk::Image< float,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >,itk::Image< float,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >,itk::Image< float,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >,itk::Image< double,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >,itk::Image< double,3 >'),
  ('LabelStatisticsOpeningImageFilter', 'itk::LabelStatisticsOpeningImageFilter', 'itkLabelStatisticsOpeningImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >,itk::Image< double,3 >'),
  ('MergeLabelMapFilter', 'itk::MergeLabelMapFilter', 'itkMergeLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('MergeLabelMapFilter', 'itk::MergeLabelMapFilter', 'itkMergeLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('PadLabelMapFilter', 'itk::PadLabelMapFilter', 'itkPadLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('PadLabelMapFilter', 'itk::PadLabelMapFilter', 'itkPadLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('RegionFromReferenceLabelMapFilter', 'itk::RegionFromReferenceLabelMapFilter', 'itkRegionFromReferenceLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('RegionFromReferenceLabelMapFilter', 'itk::RegionFromReferenceLabelMapFilter', 'itkRegionFromReferenceLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('RelabelLabelMapFilter', 'itk::RelabelLabelMapFilter', 'itkRelabelLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('RelabelLabelMapFilter', 'itk::RelabelLabelMapFilter', 'itkRelabelLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ShapeKeepNObjectsLabelMapFilter', 'itk::ShapeKeepNObjectsLabelMapFilter', 'itkShapeKeepNObjectsLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ShapeKeepNObjectsLabelMapFilter', 'itk::ShapeKeepNObjectsLabelMapFilter', 'itkShapeKeepNObjectsLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ShapeLabelMapFilter', 'itk::ShapeLabelMapFilter', 'itkShapeLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ShapeLabelMapFilter', 'itk::ShapeLabelMapFilter', 'itkShapeLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ShapeOpeningLabelMapFilter', 'itk::ShapeOpeningLabelMapFilter', 'itkShapeOpeningLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ShapeOpeningLabelMapFilter', 'itk::ShapeOpeningLabelMapFilter', 'itkShapeOpeningLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ShapeRelabelImageFilter', 'itk::ShapeRelabelImageFilter', 'itkShapeRelabelImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('ShapeRelabelImageFilter', 'itk::ShapeRelabelImageFilter', 'itkShapeRelabelImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('ShapeRelabelImageFilter', 'itk::ShapeRelabelImageFilter', 'itkShapeRelabelImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('ShapeRelabelImageFilter', 'itk::ShapeRelabelImageFilter', 'itkShapeRelabelImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('ShapeRelabelImageFilter', 'itk::ShapeRelabelImageFilter', 'itkShapeRelabelImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('ShapeRelabelImageFilter', 'itk::ShapeRelabelImageFilter', 'itkShapeRelabelImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('ShapeRelabelLabelMapFilter', 'itk::ShapeRelabelLabelMapFilter', 'itkShapeRelabelLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ShapeRelabelLabelMapFilter', 'itk::ShapeRelabelLabelMapFilter', 'itkShapeRelabelLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ShapeUniqueLabelMapFilter', 'itk::ShapeUniqueLabelMapFilter', 'itkShapeUniqueLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ShapeUniqueLabelMapFilter', 'itk::ShapeUniqueLabelMapFilter', 'itkShapeUniqueLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('ShiftScaleLabelMapFilter', 'itk::ShiftScaleLabelMapFilter', 'itkShiftScaleLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('ShiftScaleLabelMapFilter', 'itk::ShiftScaleLabelMapFilter', 'itkShiftScaleLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('StatisticsKeepNObjectsLabelMapFilter', 'itk::StatisticsKeepNObjectsLabelMapFilter', 'itkStatisticsKeepNObjectsLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('StatisticsKeepNObjectsLabelMapFilter', 'itk::StatisticsKeepNObjectsLabelMapFilter', 'itkStatisticsKeepNObjectsLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM2IUC2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned char,2 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM2IUL2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned long,2 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM2IUS2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< unsigned short,2 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM2IF2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< float,2 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM2ID2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >, itk::Image< double,2 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM3IUC3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned char,3 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM3IUL3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned long,3 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM3IUS3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< unsigned short,3 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM3IF3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< float,3 >'),
  ('StatisticsLabelMapFilter', 'itk::StatisticsLabelMapFilter', 'itkStatisticsLabelMapFilterLM3ID3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >, itk::Image< double,3 >'),
  ('StatisticsOpeningLabelMapFilter', 'itk::StatisticsOpeningLabelMapFilter', 'itkStatisticsOpeningLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('StatisticsOpeningLabelMapFilter', 'itk::StatisticsOpeningLabelMapFilter', 'itkStatisticsOpeningLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned char,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned char,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned short,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >,itk::Image< float,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >,itk::Image< float,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >,itk::Image< float,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >,itk::Image< double,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >,itk::Image< double,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >,itk::Image< double,2 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned char,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned char,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned short,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >,itk::Image< float,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >,itk::Image< float,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >,itk::Image< float,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >,itk::Image< double,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >,itk::Image< double,3 >'),
  ('StatisticsRelabelImageFilter', 'itk::StatisticsRelabelImageFilter', 'itkStatisticsRelabelImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >,itk::Image< double,3 >'),
  ('StatisticsRelabelLabelMapFilter', 'itk::StatisticsRelabelLabelMapFilter', 'itkStatisticsRelabelLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('StatisticsRelabelLabelMapFilter', 'itk::StatisticsRelabelLabelMapFilter', 'itkStatisticsRelabelLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
  ('StatisticsUniqueLabelMapFilter', 'itk::StatisticsUniqueLabelMapFilter', 'itkStatisticsUniqueLabelMapFilterLM2', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 2 > >'),
  ('StatisticsUniqueLabelMapFilter', 'itk::StatisticsUniqueLabelMapFilter', 'itkStatisticsUniqueLabelMapFilterLM3', 'itk::LabelMap< itk::StatisticsLabelObject< unsigned long, 3 > >'),
)
