depends = ('ITKPyBase', 'Numerics', 'Base', 'VXLNumerics', )
templates = (
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BSplineDecompositionImageFilter', 'itk::BSplineDecompositionImageFilter', 'itkBSplineDecompositionImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned char,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned char,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned short,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >,itk::Image< float,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >,itk::Image< float,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >,itk::Image< float,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >,itk::Image< double,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >,itk::Image< double,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >,itk::Image< double,2 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned char,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned char,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned short,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >,itk::Image< float,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >,itk::Image< float,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >,itk::Image< float,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >,itk::Image< double,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >,itk::Image< double,3 >'),
  ('LabelGeometryImageFilter', 'itk::LabelGeometryImageFilter', 'itkLabelGeometryImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >,itk::Image< double,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIF2IUC2', 'itk::Image< float,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIF2IUL2', 'itk::Image< float,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIF2IUS2', 'itk::Image< float,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterID2IUC2', 'itk::Image< double,2 >,itk::Image< unsigned char,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterID2IUL2', 'itk::Image< double,2 >,itk::Image< unsigned long,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterID2IUS2', 'itk::Image< double,2 >,itk::Image< unsigned short,2 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIF3IUC3', 'itk::Image< float,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIF3IUL3', 'itk::Image< float,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterIF3IUS3', 'itk::Image< float,3 >,itk::Image< unsigned short,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterID3IUC3', 'itk::Image< double,3 >,itk::Image< unsigned char,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterID3IUL3', 'itk::Image< double,3 >,itk::Image< unsigned long,3 >'),
  ('LabelStatisticsImageFilter', 'itk::LabelStatisticsImageFilter', 'itkLabelStatisticsImageFilterID3IUS3', 'itk::Image< double,3 >,itk::Image< unsigned short,3 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIUC2IUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIUC3IUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIUL2IUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIUL3IUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIUS2IUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIUS3IUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIF2IF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterIF3IF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterID2ID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MaximumImageFilter', 'itk::MaximumImageFilter', 'itkMaximumImageFilterID3ID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIUC2IUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIUC3IUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIUL2IUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIUL3IUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIUS2IUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIUS3IUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIF2IF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterIF3IF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterID2ID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MinimumImageFilter', 'itk::MinimumImageFilter', 'itkMinimumImageFilterID3ID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIUC2', 'itk::Image< unsigned char,2 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIUC3', 'itk::Image< unsigned char,3 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIUL2', 'itk::Image< unsigned long,2 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIUL3', 'itk::Image< unsigned long,3 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIUS2', 'itk::Image< unsigned short,2 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIUS3', 'itk::Image< unsigned short,3 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIF2', 'itk::Image< float,2 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorIF3', 'itk::Image< float,3 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorID2', 'itk::Image< double,2 >'),
  ('MinimumMaximumImageCalculator', 'itk::MinimumMaximumImageCalculator', 'itkMinimumMaximumImageCalculatorID3', 'itk::Image< double,3 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIF2', 'itk::Image< float,2 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterIF3', 'itk::Image< float,3 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterID2', 'itk::Image< double,2 >'),
  ('MinimumMaximumImageFilter', 'itk::MinimumMaximumImageFilter', 'itkMinimumMaximumImageFilterID3', 'itk::Image< double,3 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('NoiseImageFilter', 'itk::NoiseImageFilter', 'itkNoiseImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIUC2', 'itk::Image< unsigned char,2 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIUC3', 'itk::Image< unsigned char,3 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIUL2', 'itk::Image< unsigned long,2 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIUL3', 'itk::Image< unsigned long,3 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIUS2', 'itk::Image< unsigned short,2 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIUS3', 'itk::Image< unsigned short,3 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIF2', 'itk::Image< float,2 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorIF3', 'itk::Image< float,3 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorID2', 'itk::Image< double,2 >'),
  ('ScalarImageToHistogramGenerator', 'itk::Statistics::ScalarImageToHistogramGenerator', 'itkScalarImageToHistogramGeneratorID3', 'itk::Image< double,3 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIF2', 'itk::Image< float,2 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterIF3', 'itk::Image< float,3 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterID2', 'itk::Image< double,2 >'),
  ('StatisticsImageFilter', 'itk::StatisticsImageFilter', 'itkStatisticsImageFilterID3', 'itk::Image< double,3 >'),
)
