depends = ('ITKPyBase', 'Base', 'VXLNumerics', )
templates = (
  ('CurvatureFlowImageFilter', 'itk::CurvatureFlowImageFilter', 'itkCurvatureFlowImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('CurvatureFlowImageFilter', 'itk::CurvatureFlowImageFilter', 'itkCurvatureFlowImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('CurvatureFlowImageFilter', 'itk::CurvatureFlowImageFilter', 'itkCurvatureFlowImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('CurvatureFlowImageFilter', 'itk::CurvatureFlowImageFilter', 'itkCurvatureFlowImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MinMaxCurvatureFlowImageFilter', 'itk::MinMaxCurvatureFlowImageFilter', 'itkMinMaxCurvatureFlowImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MinMaxCurvatureFlowImageFilter', 'itk::MinMaxCurvatureFlowImageFilter', 'itkMinMaxCurvatureFlowImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MinMaxCurvatureFlowImageFilter', 'itk::MinMaxCurvatureFlowImageFilter', 'itkMinMaxCurvatureFlowImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MinMaxCurvatureFlowImageFilter', 'itk::MinMaxCurvatureFlowImageFilter', 'itkMinMaxCurvatureFlowImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('VotingBinaryImageFilter', 'itk::VotingBinaryImageFilter', 'itkVotingBinaryImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('AnisotropicDiffusionImageFilter', 'itk::AnisotropicDiffusionImageFilter', 'itkAnisotropicDiffusionImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BilateralImageFilter', 'itk::BilateralImageFilter', 'itkBilateralImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BinaryMedianImageFilter', 'itk::BinaryMedianImageFilter', 'itkBinaryMedianImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('BinaryMinMaxCurvatureFlowImageFilter', 'itk::BinaryMinMaxCurvatureFlowImageFilter', 'itkBinaryMinMaxCurvatureFlowImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BinaryMinMaxCurvatureFlowImageFilter', 'itk::BinaryMinMaxCurvatureFlowImageFilter', 'itkBinaryMinMaxCurvatureFlowImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BinaryMinMaxCurvatureFlowImageFilter', 'itk::BinaryMinMaxCurvatureFlowImageFilter', 'itkBinaryMinMaxCurvatureFlowImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BinaryMinMaxCurvatureFlowImageFilter', 'itk::BinaryMinMaxCurvatureFlowImageFilter', 'itkBinaryMinMaxCurvatureFlowImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('CurvatureAnisotropicDiffusionImageFilter', 'itk::CurvatureAnisotropicDiffusionImageFilter', 'itkCurvatureAnisotropicDiffusionImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('CurvatureAnisotropicDiffusionImageFilter', 'itk::CurvatureAnisotropicDiffusionImageFilter', 'itkCurvatureAnisotropicDiffusionImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('CurvatureAnisotropicDiffusionImageFilter', 'itk::CurvatureAnisotropicDiffusionImageFilter', 'itkCurvatureAnisotropicDiffusionImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('CurvatureAnisotropicDiffusionImageFilter', 'itk::CurvatureAnisotropicDiffusionImageFilter', 'itkCurvatureAnisotropicDiffusionImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('GradientAnisotropicDiffusionImageFilter', 'itk::GradientAnisotropicDiffusionImageFilter', 'itkGradientAnisotropicDiffusionImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('GradientAnisotropicDiffusionImageFilter', 'itk::GradientAnisotropicDiffusionImageFilter', 'itkGradientAnisotropicDiffusionImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('GradientAnisotropicDiffusionImageFilter', 'itk::GradientAnisotropicDiffusionImageFilter', 'itkGradientAnisotropicDiffusionImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('GradientAnisotropicDiffusionImageFilter', 'itk::GradientAnisotropicDiffusionImageFilter', 'itkGradientAnisotropicDiffusionImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MeanImageFilter', 'itk::MeanImageFilter', 'itkMeanImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MedianImageFilter', 'itk::MedianImageFilter', 'itkMedianImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('VectorCurvatureAnisotropicDiffusionImageFilter', 'itk::VectorCurvatureAnisotropicDiffusionImageFilter', 'itkVectorCurvatureAnisotropicDiffusionImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('VectorCurvatureAnisotropicDiffusionImageFilter', 'itk::VectorCurvatureAnisotropicDiffusionImageFilter', 'itkVectorCurvatureAnisotropicDiffusionImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('VectorCurvatureAnisotropicDiffusionImageFilter', 'itk::VectorCurvatureAnisotropicDiffusionImageFilter', 'itkVectorCurvatureAnisotropicDiffusionImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('VectorCurvatureAnisotropicDiffusionImageFilter', 'itk::VectorCurvatureAnisotropicDiffusionImageFilter', 'itkVectorCurvatureAnisotropicDiffusionImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('VectorGradientAnisotropicDiffusionImageFilter', 'itk::VectorGradientAnisotropicDiffusionImageFilter', 'itkVectorGradientAnisotropicDiffusionImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('VectorGradientAnisotropicDiffusionImageFilter', 'itk::VectorGradientAnisotropicDiffusionImageFilter', 'itkVectorGradientAnisotropicDiffusionImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('VectorGradientAnisotropicDiffusionImageFilter', 'itk::VectorGradientAnisotropicDiffusionImageFilter', 'itkVectorGradientAnisotropicDiffusionImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('VectorGradientAnisotropicDiffusionImageFilter', 'itk::VectorGradientAnisotropicDiffusionImageFilter', 'itkVectorGradientAnisotropicDiffusionImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('VotingBinaryHoleFillingImageFilter', 'itk::VotingBinaryHoleFillingImageFilter', 'itkVotingBinaryHoleFillingImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('VotingBinaryHoleFillingImageFilter', 'itk::VotingBinaryHoleFillingImageFilter', 'itkVotingBinaryHoleFillingImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('VotingBinaryHoleFillingImageFilter', 'itk::VotingBinaryHoleFillingImageFilter', 'itkVotingBinaryHoleFillingImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('VotingBinaryHoleFillingImageFilter', 'itk::VotingBinaryHoleFillingImageFilter', 'itkVotingBinaryHoleFillingImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('VotingBinaryHoleFillingImageFilter', 'itk::VotingBinaryHoleFillingImageFilter', 'itkVotingBinaryHoleFillingImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('VotingBinaryHoleFillingImageFilter', 'itk::VotingBinaryHoleFillingImageFilter', 'itkVotingBinaryHoleFillingImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('VotingBinaryIterativeHoleFillingImageFilter', 'itk::VotingBinaryIterativeHoleFillingImageFilter', 'itkVotingBinaryIterativeHoleFillingImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('VotingBinaryIterativeHoleFillingImageFilter', 'itk::VotingBinaryIterativeHoleFillingImageFilter', 'itkVotingBinaryIterativeHoleFillingImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('VotingBinaryIterativeHoleFillingImageFilter', 'itk::VotingBinaryIterativeHoleFillingImageFilter', 'itkVotingBinaryIterativeHoleFillingImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('VotingBinaryIterativeHoleFillingImageFilter', 'itk::VotingBinaryIterativeHoleFillingImageFilter', 'itkVotingBinaryIterativeHoleFillingImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('VotingBinaryIterativeHoleFillingImageFilter', 'itk::VotingBinaryIterativeHoleFillingImageFilter', 'itkVotingBinaryIterativeHoleFillingImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('VotingBinaryIterativeHoleFillingImageFilter', 'itk::VotingBinaryIterativeHoleFillingImageFilter', 'itkVotingBinaryIterativeHoleFillingImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
)
