depends = ('ITKPyBase', 'Base', 'VXLNumerics', )
templates = (
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ApproximateSignedDistanceMapImageFilter', 'itk::ApproximateSignedDistanceMapImageFilter', 'itkApproximateSignedDistanceMapImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >, itk::Image< float,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >, itk::Image< float,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >, itk::Image< double,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >, itk::Image< double,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('DanielssonDistanceMapImageFilter', 'itk::DanielssonDistanceMapImageFilter', 'itkDanielssonDistanceMapImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('FastChamferDistanceImageFilter', 'itk::FastChamferDistanceImageFilter', 'itkFastChamferDistanceImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >, itk::Image< double,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('SignedDanielssonDistanceMapImageFilter', 'itk::SignedDanielssonDistanceMapImageFilter', 'itkSignedDanielssonDistanceMapImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC2IF2', 'itk::Image< unsigned char,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC3IF3', 'itk::Image< unsigned char,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC2ID2', 'itk::Image< unsigned char,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUC3ID3', 'itk::Image< unsigned char,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUL2IF2', 'itk::Image< unsigned long,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUL3IF3', 'itk::Image< unsigned long,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUL2ID2', 'itk::Image< unsigned long,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUL3ID3', 'itk::Image< unsigned long,3 >, itk::Image< double,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS2IF2', 'itk::Image< unsigned short,2 >, itk::Image< float,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS3IF3', 'itk::Image< unsigned short,3 >, itk::Image< float,3 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS2ID2', 'itk::Image< unsigned short,2 >, itk::Image< double,2 >'),
  ('SignedMaurerDistanceMapImageFilter', 'itk::SignedMaurerDistanceMapImageFilter', 'itkSignedMaurerDistanceMapImageFilterIUS3ID3', 'itk::Image< unsigned short,3 >, itk::Image< double,3 >'),
)
