depends = ('ITKPyBase', 'Base', 'VXLNumerics', )
templates = (
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('AdditiveGaussianNoiseImageFilter', 'itk::AdditiveGaussianNoiseImageFilter', 'itkAdditiveGaussianNoiseImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BinaryMarkBranchingPointImageFilter', 'itk::BinaryMarkBranchingPointImageFilter', 'itkBinaryMarkBranchingPointImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('BinaryThinning3DImageFilter', 'itk::BinaryThinning3DImageFilter', 'itkBinaryThinning3DImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BinaryThinning3DImageFilter', 'itk::BinaryThinning3DImageFilter', 'itkBinaryThinning3DImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BinaryThinning3DImageFilter', 'itk::BinaryThinning3DImageFilter', 'itkBinaryThinning3DImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('DynamicThreshold3DImageFilter', 'itk::DynamicThreshold3DImageFilter', 'itkDynamicThreshold3DImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('DynamicThresholdImageFilter', 'itk::DynamicThresholdImageFilter', 'itkDynamicThresholdImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('HistogramToRunLengthFeaturesFilter', 'itk::Statistics::HistogramToRunLengthFeaturesFilter', 'itkHistogramToRunLengthFeaturesFilterHF', 'itk::Statistics::Histogram< float >'),
  ('HistogramToRunLengthFeaturesFilter', 'itk::Statistics::HistogramToRunLengthFeaturesFilter', 'itkHistogramToRunLengthFeaturesFilterHD', 'itk::Statistics::Histogram< double >'),
  ('LabelShapeImageFilter', 'itk::LabelShapeImageFilter', 'itkLabelShapeImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('LabelShapeImageFilter', 'itk::LabelShapeImageFilter', 'itkLabelShapeImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('LabelShapeImageFilter', 'itk::LabelShapeImageFilter', 'itkLabelShapeImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('LabelShapeImageFilter', 'itk::LabelShapeImageFilter', 'itkLabelShapeImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('LabelShapeImageFilter', 'itk::LabelShapeImageFilter', 'itkLabelShapeImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('LabelShapeImageFilter', 'itk::LabelShapeImageFilter', 'itkLabelShapeImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIF2IUC2', 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterIF3IUC3', 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterID2IUC2', 'itk::Image< double,2 >, itk::Image< unsigned char,2 >'),
  ('N3MRIBiasFieldCorrectionImageFilter', 'itk::N3MRIBiasFieldCorrectionImageFilter', 'itkN3MRIBiasFieldCorrectionImageFilterID3IUC3', 'itk::Image< double,3 >, itk::Image< unsigned char,3 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIUC2', 'itk::Image< unsigned char,2 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIUC3', 'itk::Image< unsigned char,3 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIUL2', 'itk::Image< unsigned long,2 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIUL3', 'itk::Image< unsigned long,3 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIUS2', 'itk::Image< unsigned short,2 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIUS3', 'itk::Image< unsigned short,3 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIF2', 'itk::Image< float,2 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorIF3', 'itk::Image< float,3 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorID2', 'itk::Image< double,2 >'),
  ('PeakSignalToNoiseRatioCalculator', 'itk::PeakSignalToNoiseRatioCalculator', 'itkPeakSignalToNoiseRatioCalculatorID3', 'itk::Image< double,3 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('SaltAndPepperNoiseImageFilter', 'itk::SaltAndPepperNoiseImageFilter', 'itkSaltAndPepperNoiseImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIF2', 'itk::Image< float,2 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterIF3', 'itk::Image< float,3 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterID2', 'itk::Image< double,2 >'),
  ('ScalarImageToRunLengthMatrixFilter', 'itk::Statistics::ScalarImageToRunLengthMatrixFilter', 'itkScalarImageToRunLengthMatrixFilterID3', 'itk::Image< double,3 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ShotNoiseImageFilter', 'itk::ShotNoiseImageFilter', 'itkShotNoiseImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('SimpleMultipleContourExtractorImageFilter', 'itk::SimpleMultipleContourExtractorImageFilter', 'itkSimpleMultipleContourExtractorImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('SimpleMultipleContourExtractorImageFilter', 'itk::SimpleMultipleContourExtractorImageFilter', 'itkSimpleMultipleContourExtractorImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('SimpleMultipleContourExtractorImageFilter', 'itk::SimpleMultipleContourExtractorImageFilter', 'itkSimpleMultipleContourExtractorImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('SimpleMultipleContourExtractorImageFilter', 'itk::SimpleMultipleContourExtractorImageFilter', 'itkSimpleMultipleContourExtractorImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('SimpleMultipleContourExtractorImageFilter', 'itk::SimpleMultipleContourExtractorImageFilter', 'itkSimpleMultipleContourExtractorImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('SimpleMultipleContourExtractorImageFilter', 'itk::SimpleMultipleContourExtractorImageFilter', 'itkSimpleMultipleContourExtractorImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUC2ICVF22', 'itk::Image< unsigned char,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUC3ICVF33', 'itk::Image< unsigned char,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUL2ICVF22', 'itk::Image< unsigned long,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUL3ICVF33', 'itk::Image< unsigned long,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUS2ICVF22', 'itk::Image< unsigned short,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUS3ICVF33', 'itk::Image< unsigned short,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIF2ICVF22', 'itk::Image< float,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIF3ICVF33', 'itk::Image< float,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterID2ICVF22', 'itk::Image< double,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterID3ICVF33', 'itk::Image< double,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUC2IVF22', 'itk::Image< unsigned char,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUC3IVF33', 'itk::Image< unsigned char,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUL2IVF22', 'itk::Image< unsigned long,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUL3IVF33', 'itk::Image< unsigned long,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUS2IVF22', 'itk::Image< unsigned short,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIUS3IVF33', 'itk::Image< unsigned short,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIF2IVF22', 'itk::Image< float,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterIF3IVF33', 'itk::Image< float,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterID2IVF22', 'itk::Image< double,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('SmoothColorFieldImageFilter', 'itk::SmoothColorFieldImageFilter', 'itkSmoothColorFieldImageFilterID3IVF33', 'itk::Image< double,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('SpeckleNoiseImageFilter', 'itk::SpeckleNoiseImageFilter', 'itkSpeckleNoiseImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
)
