depends = ()
templates = (
  ('SwigPyIterator', 'SwigPyIterator', 'SwigPyIterator'),
  ('PySwigIterator', 'SwigPyIterator', 'SwigPyIterator'),
  ('cerr', 'std::cerr', 'cerr'),
  ('cin', 'std::cin', 'cin'),
  ('clog', 'std::clog', 'clog'),
  ('cout', 'std::cout', 'cout'),
  ('cvar', 'std::cvar', 'cvar'),
  ('endl', 'std::endl', 'endl'),
  ('ends', 'std::ends', 'ends'),
  ('flush', 'std::flush', 'flush'),
  ('ios', 'std::ios', 'ios'),
  ('ios_base', 'std::ios_base', 'ios_base'),
  ('ios_base_sync_with_stdio', 'std::ios_base_sync_with_stdio', 'ios_base_sync_with_stdio'),
  ('ios_base_xalloc', 'std::ios_base_xalloc', 'ios_base_xalloc'),
  ('iostream', 'std::iostream', 'iostream'),
  ('istream', 'std::istream', 'istream'),
  ('istringstream', 'std::istringstream', 'istringstream'),
  ('ostream', 'std::ostream', 'ostream'),
  ('ostringstream', 'std::ostringstream', 'ostringstream'),
  ('streambuf', 'std::streambuf', 'streambuf'),
  ('string', 'std::string', 'string'),
  ('stringstream', 'std::stringstream', 'stringstream'),
  ('map', 'std::map', 'mapUCUC', 'unsigned char, unsigned char'),
  ('list', 'std::list', 'listUC', 'unsigned char'),
  ('set', 'std::set', 'setUC', 'unsigned char'),
  ('vector', 'std::vector', 'vectorUC', 'unsigned char'),
  ('vector', 'std::vector', 'vectorvectorUC', 'std::vector< unsigned char >'),
  ('map', 'std::map', 'mapUSUS', 'unsigned short, unsigned short'),
  ('list', 'std::list', 'listUS', 'unsigned short'),
  ('set', 'std::set', 'setUS', 'unsigned short'),
  ('vector', 'std::vector', 'vectorUS', 'unsigned short'),
  ('vector', 'std::vector', 'vectorvectorUS', 'std::vector< unsigned short >'),
  ('map', 'std::map', 'mapULUL', 'unsigned long, unsigned long'),
  ('list', 'std::list', 'listUL', 'unsigned long'),
  ('set', 'std::set', 'setUL', 'unsigned long'),
  ('vector', 'std::vector', 'vectorUL', 'unsigned long'),
  ('vector', 'std::vector', 'vectorvectorUL', 'std::vector< unsigned long >'),
  ('map', 'std::map', 'mapSCSC', 'signed char, signed char'),
  ('list', 'std::list', 'listSC', 'signed char'),
  ('set', 'std::set', 'setSC', 'signed char'),
  ('vector', 'std::vector', 'vectorSC', 'signed char'),
  ('vector', 'std::vector', 'vectorvectorSC', 'std::vector< signed char >'),
  ('map', 'std::map', 'mapSSSS', 'signed short, signed short'),
  ('list', 'std::list', 'listSS', 'signed short'),
  ('set', 'std::set', 'setSS', 'signed short'),
  ('vector', 'std::vector', 'vectorSS', 'signed short'),
  ('vector', 'std::vector', 'vectorvectorSS', 'std::vector< signed short >'),
  ('map', 'std::map', 'mapSLSL', 'signed long, signed long'),
  ('list', 'std::list', 'listSL', 'signed long'),
  ('set', 'std::set', 'setSL', 'signed long'),
  ('vector', 'std::vector', 'vectorSL', 'signed long'),
  ('vector', 'std::vector', 'vectorvectorSL', 'std::vector< signed long >'),
  ('map', 'std::map', 'mapFF', 'float, float'),
  ('list', 'std::list', 'listF', 'float'),
  ('set', 'std::set', 'setF', 'float'),
  ('vector', 'std::vector', 'vectorF', 'float'),
  ('vector', 'std::vector', 'vectorvectorF', 'std::vector< float >'),
  ('map', 'std::map', 'mapDD', 'double, double'),
  ('list', 'std::list', 'listD', 'double'),
  ('set', 'std::set', 'setD', 'double'),
  ('vector', 'std::vector', 'vectorD', 'double'),
  ('vector', 'std::vector', 'vectorvectorD', 'std::vector< double >'),
  ('map', 'std::map', 'mapULD', 'unsigned long, double'),
  ('vector', 'std::vector', 'vectorsetUL', 'std::set< unsigned long >'),
  ('map', 'std::map', 'mapsetUL', 'unsigned long, std::set< unsigned long >'),
)
