depends = ('ITKPyBase', 'Base', )
templates = (
  ('DefaultDynamicMeshTraits', 'itk::DefaultDynamicMeshTraits', 'itkDefaultDynamicMeshTraitsD22DD', 'double,2,2,double,double'),
  ('DefaultDynamicMeshTraits', 'itk::DefaultDynamicMeshTraits', 'itkDefaultDynamicMeshTraitsD22D', 'double,2,2,double'),
  ('DefaultDynamicMeshTraits', 'itk::DefaultDynamicMeshTraits', 'itkDefaultDynamicMeshTraitsD33DD', 'double,3,3,double,double'),
  ('DefaultDynamicMeshTraits', 'itk::DefaultDynamicMeshTraits', 'itkDefaultDynamicMeshTraitsD33D', 'double,3,3,double'),
  ('DefaultStaticMeshTraits', 'itk::DefaultStaticMeshTraits', 'itkDefaultStaticMeshTraitsD22DD', 'double,2,2,double,double'),
  ('DefaultStaticMeshTraits', 'itk::DefaultStaticMeshTraits', 'itkDefaultStaticMeshTraitsD22D', 'double,2,2,double'),
  ('DefaultStaticMeshTraits', 'itk::DefaultStaticMeshTraits', 'itkDefaultStaticMeshTraitsD33DD', 'double,3,3,double,double'),
  ('DefaultStaticMeshTraits', 'itk::DefaultStaticMeshTraits', 'itkDefaultStaticMeshTraitsD33D', 'double,3,3,double'),
  ('QuadEdge', 'itk::QuadEdge', 'itkQuadEdge'),
  ('GeometricalQuadEdge', 'itk::GeometricalQuadEdge', 'itkGeometricalQuadEdgeULULBBF', 'unsigned long, unsigned long, bool, bool, true'),
  ('GeometricalQuadEdge', 'itk::GeometricalQuadEdge', 'itkGeometricalQuadEdgeULULBBT', 'unsigned long, unsigned long, bool, bool, false'),
  ('QuadEdgeMeshPoint', 'itk::QuadEdgeMeshPoint', 'itkQuadEdgeMeshPointF2', 'float, 2'),
  ('QuadEdgeMeshPoint', 'itk::QuadEdgeMeshPoint', 'itkQuadEdgeMeshPointF3', 'float, 3'),
  ('QuadEdgeMeshTraits', 'itk::QuadEdgeMeshTraits', 'itkQuadEdgeMeshTraitsD2BBFF', 'double, 2, bool, bool, float, float'),
  ('QuadEdgeMeshTraits', 'itk::QuadEdgeMeshTraits', 'itkQuadEdgeMeshTraitsD3BBFF', 'double, 3, bool, bool, float, float'),
  ('QuadEdgeMeshCellTraitsInfo', 'itk::QuadEdgeMeshCellTraitsInfo', 'itkQuadEdgeMeshCellTraitsInfo2', '2'),
  ('QuadEdgeMeshCellTraitsInfo', 'itk::QuadEdgeMeshCellTraitsInfo', 'itkQuadEdgeMeshCellTraitsInfo3', '3'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDQEMCTI2', 'double, itk::QuadEdgeMeshCellTraitsInfo< 2 >'),
  ('CellInterface', 'itk::CellInterface', 'itkCellInterfaceDQEMCTI3', 'double, itk::QuadEdgeMeshCellTraitsInfo< 3 >'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULQEMPF2', 'unsigned long, itk::QuadEdgeMeshPoint< float, 2 >'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIDQEMCTI2', 'unsigned long, itk::CellInterface< double, itk::QuadEdgeMeshCellTraitsInfo< 2 > >*'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULQEMPF3', 'unsigned long, itk::QuadEdgeMeshPoint< float, 3 >'),
  ('MapContainer', 'itk::MapContainer', 'itkMapContainerULCIDQEMCTI3', 'unsigned long, itk::CellInterface< double, itk::QuadEdgeMeshCellTraitsInfo< 3 > >*'),
  ('BoundingBox', 'itk::BoundingBox', 'itkBoundingBoxUL2FMCULQEMPF2', 'unsigned long, 2, float, itk::MapContainer< unsigned long, itk::QuadEdgeMeshPoint< float, 2 > >'),
  ('BoundingBox', 'itk::BoundingBox', 'itkBoundingBoxUL3FMCULQEMPF3', 'unsigned long, 3, float, itk::MapContainer< unsigned long, itk::QuadEdgeMeshPoint< float, 3 > >'),
  ('map', 'std::map', 'mapULitkQuadEdgeMeshPointF2', 'unsigned long, itk::QuadEdgeMeshPoint< float, 2 >'),
  ('map', 'std::map', 'mapULitkCellInterfaceDQEMCTI2', 'unsigned long, itk::CellInterface< double, itk::QuadEdgeMeshCellTraitsInfo< 2 > >*'),
  ('map', 'std::map', 'mapULitkQuadEdgeMeshPointF3', 'unsigned long, itk::QuadEdgeMeshPoint< float, 3 >'),
  ('map', 'std::map', 'mapULitkCellInterfaceDQEMCTI3', 'unsigned long, itk::CellInterface< double, itk::QuadEdgeMeshCellTraitsInfo< 3 > >*'),
  ('QuadEdgeMeshLineCell', 'itk::QuadEdgeMeshLineCell', 'itkQuadEdgeMeshLineCellCIDQEMCTIF2', 'itk::CellInterface< double, itk::QuadEdgeMeshCellTraitsInfo< 2 > >'),
  ('QuadEdgeMeshLineCell', 'itk::QuadEdgeMeshLineCell', 'itkQuadEdgeMeshLineCellCIDQEMCTIF3', 'itk::CellInterface< double, itk::QuadEdgeMeshCellTraitsInfo< 3 > >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetD2S', 'double,2,itk::DefaultStaticMeshTraits< double,2,2,double >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetD2D', 'double,2,itk::DefaultDynamicMeshTraits< double,2,2,double >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetPD22S', 'itk::Point< double,2 >,2,itk::DefaultStaticMeshTraits< double,2,2,double,double >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetD2Q', 'double,2,itk::QuadEdgeMeshTraits< double,2,bool,bool,float,float >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetD3S', 'double,3,itk::DefaultStaticMeshTraits< double,3,3,double >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetD3D', 'double,3,itk::DefaultDynamicMeshTraits< double,3,3,double >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetPD33S', 'itk::Point< double,3 >,3,itk::DefaultStaticMeshTraits< double,3,3,double,double >'),
  ('PointSet', 'itk::PointSet', 'itkPointSetD3Q', 'double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float >'),
  ('Mesh', 'itk::Mesh', 'itkMeshD2S', 'double,2,itk::DefaultStaticMeshTraits< double,2,2,double >'),
  ('Mesh', 'itk::Mesh', 'itkMeshD2D', 'double,2,itk::DefaultDynamicMeshTraits< double,2,2,double >'),
  ('Mesh', 'itk::Mesh', 'itkMeshD2Q', 'double,2,itk::QuadEdgeMeshTraits< double,2,bool,bool,float,float >'),
  ('Mesh', 'itk::Mesh', 'itkMeshD3S', 'double,3,itk::DefaultStaticMeshTraits< double,3,3,double >'),
  ('Mesh', 'itk::Mesh', 'itkMeshD3D', 'double,3,itk::DefaultDynamicMeshTraits< double,3,3,double >'),
  ('Mesh', 'itk::Mesh', 'itkMeshD3Q', 'double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float >'),
  ('QuadEdgeMesh', 'itk::QuadEdgeMesh', 'itkQuadEdgeMeshD3S', 'double,3'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMD2Q', 'itk::Mesh< double,2,itk::QuadEdgeMeshTraits< double,2,bool,bool,float,float > >'),
  ('MeshSource', 'itk::MeshSource', 'itkMeshSourceMD3Q', 'itk::Mesh< double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float > >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC2MD2Q', 'itk::Image< unsigned char,2 >, itk::Mesh< double,2,itk::QuadEdgeMeshTraits< double,2,bool,bool,float,float > >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUL2MD2Q', 'itk::Image< unsigned long,2 >, itk::Mesh< double,2,itk::QuadEdgeMeshTraits< double,2,bool,bool,float,float > >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS2MD2Q', 'itk::Image< unsigned short,2 >, itk::Mesh< double,2,itk::QuadEdgeMeshTraits< double,2,bool,bool,float,float > >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUC3MD3Q', 'itk::Image< unsigned char,3 >, itk::Mesh< double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float > >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUL3MD3Q', 'itk::Image< unsigned long,3 >, itk::Mesh< double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float > >'),
  ('ImageToMeshFilter', 'itk::ImageToMeshFilter', 'itkImageToMeshFilterIUS3MD3Q', 'itk::Image< unsigned short,3 >, itk::Mesh< double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float > >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUC3MD3Q', 'itk::Image< unsigned char,3 >, itk::Mesh< double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float > >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUL3MD3Q', 'itk::Image< unsigned long,3 >, itk::Mesh< double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float > >'),
  ('BinaryMask3DMeshSource', 'itk::BinaryMask3DMeshSource', 'itkBinaryMask3DMeshSourceIUS3MD3Q', 'itk::Image< unsigned short,3 >, itk::Mesh< double,3,itk::QuadEdgeMeshTraits< double,3,bool,bool,float,float > >'),
)
