depends = ('ITKPyBase', 'Base', 'VXLNumerics', )
templates = (
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIRGBUS2IRGBUS2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIRGBUS3IRGBUS3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< itk::RGBPixel< unsigned short >,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIRGBAUS2IRGBAUS2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< itk::RGBAPixel< unsigned short >,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIRGBAUS3IRGBAUS3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< itk::RGBAPixel< unsigned short >,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterICF2ICF2', 'itk::Image< std::complex< float >,2 >, itk::Image< std::complex< float >,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterICF3ICF3', 'itk::Image< std::complex< float >,3 >, itk::Image< std::complex< float >,3 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUC3IUC2', 'itk::Image< unsigned char,3 >,itk::Image< unsigned char,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUL3IUL2', 'itk::Image< unsigned long,3 >,itk::Image< unsigned long,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIUS3IUS2', 'itk::Image< unsigned short,3 >,itk::Image< unsigned short,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIF3IF2', 'itk::Image< float,3 >,itk::Image< float,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterID3ID2', 'itk::Image< double,3 >,itk::Image< double,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterIRGBUS3IRGBUS2', 'itk::Image< itk::RGBPixel< unsigned short >,3 >,itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('ExtractImageFilter', 'itk::ExtractImageFilter', 'itkExtractImageFilterICF3ICF2', 'itk::Image< std::complex< float >,3 >,itk::Image< std::complex< float >,2 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('AccumulateImageFilter', 'itk::AccumulateImageFilter', 'itkAccumulateImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BSplineDownsampleImageFilter', 'itk::BSplineDownsampleImageFilter', 'itkBSplineDownsampleImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('BSplineUpsampleImageFilter', 'itk::BSplineUpsampleImageFilter', 'itkBSplineUpsampleImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIRGBUS2IRGBUS2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIRGBUS3IRGBUS3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< itk::RGBPixel< unsigned short >,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIRGBAUS2IRGBAUS2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< itk::RGBAPixel< unsigned short >,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIRGBAUS3IRGBAUS3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< itk::RGBAPixel< unsigned short >,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterICF2ICF2', 'itk::Image< std::complex< float >,2 >, itk::Image< std::complex< float >,2 >'),
  ('ConstantPadImageFilter', 'itk::ConstantPadImageFilter', 'itkConstantPadImageFilterICF3ICF3', 'itk::Image< std::complex< float >,3 >, itk::Image< std::complex< float >,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIRGBUS2IRGBUS2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIRGBUS3IRGBUS3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< itk::RGBPixel< unsigned short >,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIRGBAUS2IRGBAUS2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< itk::RGBAPixel< unsigned short >,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIRGBAUS3IRGBAUS3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< itk::RGBAPixel< unsigned short >,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterICF2ICF2', 'itk::Image< std::complex< float >,2 >, itk::Image< std::complex< float >,2 >'),
  ('CropImageFilter', 'itk::CropImageFilter', 'itkCropImageFilterICF3ICF3', 'itk::Image< std::complex< float >,3 >, itk::Image< std::complex< float >,3 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ExpandImageFilter', 'itk::ExpandImageFilter', 'itkExpandImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIRGBUS2IRGBUS2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIRGBUS3IRGBUS3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< itk::RGBPixel< unsigned short >,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIRGBAUS2IRGBAUS2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< itk::RGBAPixel< unsigned short >,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIRGBAUS3IRGBAUS3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< itk::RGBAPixel< unsigned short >,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterICF2ICF2', 'itk::Image< std::complex< float >,2 >, itk::Image< std::complex< float >,2 >'),
  ('MirrorPadImageFilter', 'itk::MirrorPadImageFilter', 'itkMirrorPadImageFilterICF3ICF3', 'itk::Image< std::complex< float >,3 >, itk::Image< std::complex< float >,3 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('MultiResolutionPyramidImageFilter', 'itk::MultiResolutionPyramidImageFilter', 'itkMultiResolutionPyramidImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('RecursiveMultiResolutionPyramidImageFilter', 'itk::RecursiveMultiResolutionPyramidImageFilter', 'itkRecursiveMultiResolutionPyramidImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ShrinkImageFilter', 'itk::ShrinkImageFilter', 'itkShrinkImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('VectorExpandImageFilter', 'itk::VectorExpandImageFilter', 'itkVectorExpandImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('VectorExpandImageFilter', 'itk::VectorExpandImageFilter', 'itkVectorExpandImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIRGBUS2IRGBUS2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< itk::RGBPixel< unsigned short >,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIRGBUS3IRGBUS3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< itk::RGBPixel< unsigned short >,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIRGBAUS2IRGBAUS2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< itk::RGBAPixel< unsigned short >,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIRGBAUS3IRGBAUS3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< itk::RGBAPixel< unsigned short >,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIVF22IVF22', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< itk::Vector< float,2 >,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIVF33IVF33', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< itk::Vector< float,3 >,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterICVF22ICVF22', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< itk::CovariantVector< float,2 >,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterICVF33ICVF33', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< itk::CovariantVector< float,3 >,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterICF2ICF2', 'itk::Image< std::complex< float >,2 >, itk::Image< std::complex< float >,2 >'),
  ('WrapPadImageFilter', 'itk::WrapPadImageFilter', 'itkWrapPadImageFilterICF3ICF3', 'itk::Image< std::complex< float >,3 >, itk::Image< std::complex< float >,3 >'),
)
