depends = ('ITKPyBase', 'Base', 'VXLNumerics', )
templates = (
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2UCFF', 'itk::VectorImage< unsigned char,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2UCDD', 'itk::VectorImage< unsigned char,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2ULFF', 'itk::VectorImage< unsigned char,2 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2ULDD', 'itk::VectorImage< unsigned char,2 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2USFF', 'itk::VectorImage< unsigned char,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC2USDD', 'itk::VectorImage< unsigned char,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL2UCFF', 'itk::VectorImage< unsigned long,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL2UCDD', 'itk::VectorImage< unsigned long,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL2ULFF', 'itk::VectorImage< unsigned long,2 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL2ULDD', 'itk::VectorImage< unsigned long,2 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL2USFF', 'itk::VectorImage< unsigned long,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL2USDD', 'itk::VectorImage< unsigned long,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2UCFF', 'itk::VectorImage< unsigned short,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2UCDD', 'itk::VectorImage< unsigned short,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2ULFF', 'itk::VectorImage< unsigned short,2 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2ULDD', 'itk::VectorImage< unsigned short,2 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2USFF', 'itk::VectorImage< unsigned short,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS2USDD', 'itk::VectorImage< unsigned short,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2UCFF', 'itk::VectorImage< float,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2UCDD', 'itk::VectorImage< float,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2ULFF', 'itk::VectorImage< float,2 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2ULDD', 'itk::VectorImage< float,2 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2USFF', 'itk::VectorImage< float,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF2USDD', 'itk::VectorImage< float,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2UCFF', 'itk::VectorImage< double,2 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2UCDD', 'itk::VectorImage< double,2 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2ULFF', 'itk::VectorImage< double,2 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2ULDD', 'itk::VectorImage< double,2 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2USFF', 'itk::VectorImage< double,2 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID2USDD', 'itk::VectorImage< double,2 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3UCFF', 'itk::VectorImage< unsigned char,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3UCDD', 'itk::VectorImage< unsigned char,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3ULFF', 'itk::VectorImage< unsigned char,3 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3ULDD', 'itk::VectorImage< unsigned char,3 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3USFF', 'itk::VectorImage< unsigned char,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUC3USDD', 'itk::VectorImage< unsigned char,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL3UCFF', 'itk::VectorImage< unsigned long,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL3UCDD', 'itk::VectorImage< unsigned long,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL3ULFF', 'itk::VectorImage< unsigned long,3 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL3ULDD', 'itk::VectorImage< unsigned long,3 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL3USFF', 'itk::VectorImage< unsigned long,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUL3USDD', 'itk::VectorImage< unsigned long,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3UCFF', 'itk::VectorImage< unsigned short,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3UCDD', 'itk::VectorImage< unsigned short,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3ULFF', 'itk::VectorImage< unsigned short,3 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3ULDD', 'itk::VectorImage< unsigned short,3 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3USFF', 'itk::VectorImage< unsigned short,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIUS3USDD', 'itk::VectorImage< unsigned short,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3UCFF', 'itk::VectorImage< float,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3UCDD', 'itk::VectorImage< float,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3ULFF', 'itk::VectorImage< float,3 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3ULDD', 'itk::VectorImage< float,3 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3USFF', 'itk::VectorImage< float,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVIF3USDD', 'itk::VectorImage< float,3 >, unsigned short, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3UCFF', 'itk::VectorImage< double,3 >, unsigned char, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3UCDD', 'itk::VectorImage< double,3 >, unsigned char, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3ULFF', 'itk::VectorImage< double,3 >, unsigned long, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3ULDD', 'itk::VectorImage< double,3 >, unsigned long, double, double'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3USFF', 'itk::VectorImage< double,3 >, unsigned short, float, float'),
  ('BayesianClassifierImageFilter', 'itk::BayesianClassifierImageFilter', 'itkBayesianClassifierImageFilterVID3USDD', 'itk::VectorImage< double,3 >, unsigned short, double, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC2F', 'itk::Image< unsigned char,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC2D', 'itk::Image< unsigned char,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUL2F', 'itk::Image< unsigned long,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUL2D', 'itk::Image< unsigned long,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS2F', 'itk::Image< unsigned short,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS2D', 'itk::Image< unsigned short,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF2F', 'itk::Image< float,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF2D', 'itk::Image< float,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID2F', 'itk::Image< double,2 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID2D', 'itk::Image< double,2 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC3F', 'itk::Image< unsigned char,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUC3D', 'itk::Image< unsigned char,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUL3F', 'itk::Image< unsigned long,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUL3D', 'itk::Image< unsigned long,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS3F', 'itk::Image< unsigned short,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIUS3D', 'itk::Image< unsigned short,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF3F', 'itk::Image< float,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterIF3D', 'itk::Image< float,3 >, double'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID3F', 'itk::Image< double,3 >, float'),
  ('BayesianClassifierInitializationImageFilter', 'itk::BayesianClassifierInitializationImageFilter', 'itkBayesianClassifierInitializationImageFilterID3D', 'itk::Image< double,3 >, double'),
  ('ChangeLabelImageFilter', 'itk::ChangeLabelImageFilter', 'itkChangeLabelImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ChangeLabelImageFilter', 'itk::ChangeLabelImageFilter', 'itkChangeLabelImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ChangeLabelImageFilter', 'itk::ChangeLabelImageFilter', 'itkChangeLabelImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ChangeLabelImageFilter', 'itk::ChangeLabelImageFilter', 'itkChangeLabelImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ChangeLabelImageFilter', 'itk::ChangeLabelImageFilter', 'itkChangeLabelImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ChangeLabelImageFilter', 'itk::ChangeLabelImageFilter', 'itkChangeLabelImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIF2IUC2', 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIF3IUC3', 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIF2IUL2', 'itk::Image< float,2 >, itk::Image< unsigned long,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIF3IUL3', 'itk::Image< float,3 >, itk::Image< unsigned long,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIF2IUS2', 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterIF3IUS3', 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterID2IUC2', 'itk::Image< double,2 >, itk::Image< unsigned char,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterID3IUC3', 'itk::Image< double,3 >, itk::Image< unsigned char,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterID2IUL2', 'itk::Image< double,2 >, itk::Image< unsigned long,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterID3IUL3', 'itk::Image< double,3 >, itk::Image< unsigned long,3 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterID2IUS2', 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('ConfidenceConnectedImageFilter', 'itk::ConfidenceConnectedImageFilter', 'itkConfidenceConnectedImageFilterID3IUS3', 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIVF22IUC2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned char,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIVF33IUC3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned char,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIVF22IUL2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned long,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIVF33IUL3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned long,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIVF22IUS2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned short,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterIVF33IUS3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned short,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterICVF22IUC2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned char,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterICVF33IUC3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned char,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterICVF22IUL2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned long,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterICVF33IUL3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned long,3 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterICVF22IUS2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned short,2 >'),
  ('ConnectedComponentImageFilter', 'itk::ConnectedComponentImageFilter', 'itkConnectedComponentImageFilterICVF33IUS3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned short,3 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ConnectedThresholdImageFilter', 'itk::ConnectedThresholdImageFilter', 'itkConnectedThresholdImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF2IUC2', 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF3IUC3', 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF2IUL2', 'itk::Image< float,2 >, itk::Image< unsigned long,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF3IUL3', 'itk::Image< float,3 >, itk::Image< unsigned long,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF2IUS2', 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterIF3IUS3', 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID2IUC2', 'itk::Image< double,2 >, itk::Image< unsigned char,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID3IUC3', 'itk::Image< double,3 >, itk::Image< unsigned char,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID2IUL2', 'itk::Image< double,2 >, itk::Image< unsigned long,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID3IUL3', 'itk::Image< double,3 >, itk::Image< unsigned long,3 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID2IUS2', 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('DoubleThresholdImageFilter', 'itk::DoubleThresholdImageFilter', 'itkDoubleThresholdImageFilterID3IUS3', 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('HardConnectedComponentImageFilter', 'itk::HardConnectedComponentImageFilter', 'itkHardConnectedComponentImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('IsolatedConnectedImageFilter', 'itk::IsolatedConnectedImageFilter', 'itkIsolatedConnectedImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('IsolatedWatershedImageFilter', 'itk::IsolatedWatershedImageFilter', 'itkIsolatedWatershedImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('LabelVotingImageFilter', 'itk::LabelVotingImageFilter', 'itkLabelVotingImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('LabelVotingImageFilter', 'itk::LabelVotingImageFilter', 'itkLabelVotingImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('LabelVotingImageFilter', 'itk::LabelVotingImageFilter', 'itkLabelVotingImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('LabelVotingImageFilter', 'itk::LabelVotingImageFilter', 'itkLabelVotingImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('LabelVotingImageFilter', 'itk::LabelVotingImageFilter', 'itkLabelVotingImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('LabelVotingImageFilter', 'itk::LabelVotingImageFilter', 'itkLabelVotingImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('NeighborhoodConnectedImageFilter', 'itk::NeighborhoodConnectedImageFilter', 'itkNeighborhoodConnectedImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('OtsuMultipleThresholdsImageFilter', 'itk::OtsuMultipleThresholdsImageFilter', 'itkOtsuMultipleThresholdsImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIUC2', 'itk::Image< unsigned char,2 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIUC3', 'itk::Image< unsigned char,3 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIUL2', 'itk::Image< unsigned long,2 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIUL3', 'itk::Image< unsigned long,3 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIUS2', 'itk::Image< unsigned short,2 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIUS3', 'itk::Image< unsigned short,3 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIF2', 'itk::Image< float,2 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorIF3', 'itk::Image< float,3 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorID2', 'itk::Image< double,2 >'),
  ('OtsuThresholdImageCalculator', 'itk::OtsuThresholdImageCalculator', 'itkOtsuThresholdImageCalculatorID3', 'itk::Image< double,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('OtsuThresholdImageFilter', 'itk::OtsuThresholdImageFilter', 'itkOtsuThresholdImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >'),
  ('RelabelComponentImageFilter', 'itk::RelabelComponentImageFilter', 'itkRelabelComponentImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarConnectedComponentImageFilter', 'itk::ScalarConnectedComponentImageFilter', 'itkScalarConnectedComponentImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarConnectedComponentImageFilter', 'itk::ScalarConnectedComponentImageFilter', 'itkScalarConnectedComponentImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarConnectedComponentImageFilter', 'itk::ScalarConnectedComponentImageFilter', 'itkScalarConnectedComponentImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ScalarConnectedComponentImageFilter', 'itk::ScalarConnectedComponentImageFilter', 'itkScalarConnectedComponentImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ScalarConnectedComponentImageFilter', 'itk::ScalarConnectedComponentImageFilter', 'itkScalarConnectedComponentImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarConnectedComponentImageFilter', 'itk::ScalarConnectedComponentImageFilter', 'itkScalarConnectedComponentImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC2IUL2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned long,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC3IUL3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned long,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC2IUS2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUC3IUS3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUL2IUC2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUL3IUC3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUL2IUS2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUL3IUS3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS2IUC2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS3IUC3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS2IUL2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned long,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS3IUL3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned long,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF2IUC2', 'itk::Image< float,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF3IUC3', 'itk::Image< float,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF2IUL2', 'itk::Image< float,2 >, itk::Image< unsigned long,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF3IUL3', 'itk::Image< float,3 >, itk::Image< unsigned long,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF2IUS2', 'itk::Image< float,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterIF3IUS3', 'itk::Image< float,3 >, itk::Image< unsigned short,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID2IUC2', 'itk::Image< double,2 >, itk::Image< unsigned char,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID3IUC3', 'itk::Image< double,3 >, itk::Image< unsigned char,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID2IUL2', 'itk::Image< double,2 >, itk::Image< unsigned long,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID3IUL3', 'itk::Image< double,3 >, itk::Image< unsigned long,3 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID2IUS2', 'itk::Image< double,2 >, itk::Image< unsigned short,2 >'),
  ('ScalarImageKmeansImageFilter', 'itk::ScalarImageKmeansImageFilter', 'itkScalarImageKmeansImageFilterID3IUS3', 'itk::Image< double,3 >, itk::Image< unsigned short,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIF2', 'itk::Image< float,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterIF3', 'itk::Image< float,3 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterID2', 'itk::Image< double,2 >'),
  ('ThresholdImageFilter', 'itk::ThresholdImageFilter', 'itkThresholdImageFilterID3', 'itk::Image< double,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUC3IUC3', 'itk::Image< unsigned char,3 >, itk::Image< unsigned char,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUL3IUL3', 'itk::Image< unsigned long,3 >, itk::Image< unsigned long,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIUS3IUS3', 'itk::Image< unsigned short,3 >, itk::Image< unsigned short,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIF2IF2', 'itk::Image< float,2 >, itk::Image< float,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterIF3IF3', 'itk::Image< float,3 >, itk::Image< float,3 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterID2ID2', 'itk::Image< double,2 >, itk::Image< double,2 >'),
  ('ThresholdLabelerImageFilter', 'itk::ThresholdLabelerImageFilter', 'itkThresholdLabelerImageFilterID3ID3', 'itk::Image< double,3 >, itk::Image< double,3 >'),
  ('ThresholdMaximumConnectedComponentsImageFilter', 'itk::ThresholdMaximumConnectedComponentsImageFilter', 'itkThresholdMaximumConnectedComponentsImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('ThresholdMaximumConnectedComponentsImageFilter', 'itk::ThresholdMaximumConnectedComponentsImageFilter', 'itkThresholdMaximumConnectedComponentsImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('ThresholdMaximumConnectedComponentsImageFilter', 'itk::ThresholdMaximumConnectedComponentsImageFilter', 'itkThresholdMaximumConnectedComponentsImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('ThresholdMaximumConnectedComponentsImageFilter', 'itk::ThresholdMaximumConnectedComponentsImageFilter', 'itkThresholdMaximumConnectedComponentsImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('ThresholdMaximumConnectedComponentsImageFilter', 'itk::ThresholdMaximumConnectedComponentsImageFilter', 'itkThresholdMaximumConnectedComponentsImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('ThresholdMaximumConnectedComponentsImageFilter', 'itk::ThresholdMaximumConnectedComponentsImageFilter', 'itkThresholdMaximumConnectedComponentsImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIF2', 'itk::Image< float,2 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterIF3', 'itk::Image< float,3 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterID2', 'itk::Image< double,2 >'),
  ('TobogganImageFilter', 'itk::TobogganImageFilter', 'itkTobogganImageFilterID3', 'itk::Image< double,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBUS2IUC2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< unsigned char,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBUS3IUC3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< unsigned char,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBUS2IUL2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< unsigned long,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBUS3IUL3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< unsigned long,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBUS2IUS2', 'itk::Image< itk::RGBPixel< unsigned short >,2 >, itk::Image< unsigned short,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBUS3IUS3', 'itk::Image< itk::RGBPixel< unsigned short >,3 >, itk::Image< unsigned short,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBAUS2IUC2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< unsigned char,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBAUS3IUC3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< unsigned char,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBAUS2IUL2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< unsigned long,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBAUS3IUL3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< unsigned long,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBAUS2IUS2', 'itk::Image< itk::RGBAPixel< unsigned short >,2 >, itk::Image< unsigned short,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIRGBAUS3IUS3', 'itk::Image< itk::RGBAPixel< unsigned short >,3 >, itk::Image< unsigned short,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIVF22IUC2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned char,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIVF33IUC3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned char,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIVF22IUL2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned long,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIVF33IUL3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned long,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIVF22IUS2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned short,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterIVF33IUS3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned short,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterICVF22IUC2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned char,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterICVF33IUC3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned char,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterICVF22IUL2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned long,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterICVF33IUL3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned long,3 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterICVF22IUS2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned short,2 >'),
  ('VectorConfidenceConnectedImageFilter', 'itk::VectorConfidenceConnectedImageFilter', 'itkVectorConfidenceConnectedImageFilterICVF33IUS3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned short,3 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterIVF22IUC2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned char,2 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterIVF33IUC3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned char,3 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterIVF22IUL2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned long,2 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterIVF33IUL3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned long,3 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterIVF22IUS2', 'itk::Image< itk::Vector< float,2 >,2 >, itk::Image< unsigned short,2 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterIVF33IUS3', 'itk::Image< itk::Vector< float,3 >,3 >, itk::Image< unsigned short,3 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterICVF22IUC2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned char,2 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterICVF33IUC3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned char,3 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterICVF22IUL2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned long,2 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterICVF33IUL3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned long,3 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterICVF22IUS2', 'itk::Image< itk::CovariantVector< float,2 >,2 >, itk::Image< unsigned short,2 >'),
  ('VectorConnectedComponentImageFilter', 'itk::VectorConnectedComponentImageFilter', 'itkVectorConnectedComponentImageFilterICVF33IUS3', 'itk::Image< itk::CovariantVector< float,3 >,3 >, itk::Image< unsigned short,3 >'),
  ('VoronoiSegmentationImageFilter', 'itk::VoronoiSegmentationImageFilter', 'itkVoronoiSegmentationImageFilterIUC2IUC2IUC2', 'itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >, itk::Image< unsigned char,2 >'),
  ('VoronoiSegmentationImageFilter', 'itk::VoronoiSegmentationImageFilter', 'itkVoronoiSegmentationImageFilterIUL2IUL2IUL2', 'itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >, itk::Image< unsigned long,2 >'),
  ('VoronoiSegmentationImageFilter', 'itk::VoronoiSegmentationImageFilter', 'itkVoronoiSegmentationImageFilterIUS2IUS2IUS2', 'itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >, itk::Image< unsigned short,2 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIUC2', 'itk::Image< unsigned char,2 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIUC3', 'itk::Image< unsigned char,3 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIUL2', 'itk::Image< unsigned long,2 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIUL3', 'itk::Image< unsigned long,3 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIUS2', 'itk::Image< unsigned short,2 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIUS3', 'itk::Image< unsigned short,3 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIF2', 'itk::Image< float,2 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterIF3', 'itk::Image< float,3 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterID2', 'itk::Image< double,2 >'),
  ('WatershedImageFilter', 'itk::WatershedImageFilter', 'itkWatershedImageFilterID3', 'itk::Image< double,3 >'),
)
