depends = ('ITKPyBase', )
templates = (
  ('vcl_complex', 'vcl_complex', 'vcl_complexF', 'float'),
  ('complex', 'std::complex', 'vcl_complexF', 'float'),
  ('vcl_complex', 'vcl_complex', 'vcl_complexD', 'double'),
  ('complex', 'std::complex', 'vcl_complexD', 'double'),
  ('vcl_complex', 'vcl_complex', 'vcl_complexLD', 'long double'),
  ('complex', 'std::complex', 'vcl_complexLD', 'long double'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixD', 'double'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrix_vcl_complexD', 'vcl_complex<double>'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixF', 'float'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrix_vcl_complexF', 'vcl_complex<float>'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixSI', 'signed int'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixSL', 'signed long'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixLD', 'long double'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrix_vcl_complexLD', 'vcl_complex<long double>'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixSC', 'signed char'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixUC', 'unsigned char'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixUI', 'unsigned int'),
  ('vnl_matrix', 'vnl_matrix', 'vnl_matrixUL', 'unsigned long'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorD', 'double'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorF', 'float'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorSI', 'signed int'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorSL', 'signed long'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorLD', 'long double'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorSC', 'signed char'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorUC', 'unsigned char'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorUS', 'unsigned short'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorUI', 'unsigned int'),
  ('vnl_vector', 'vnl_vector', 'vnl_vectorUL', 'unsigned long'),
  ('vnl_vector', 'vnl_vector', 'vnl_vector_vcl_complexD', 'vcl_complex<double>'),
  ('vnl_vector', 'vnl_vector', 'vnl_vector_vcl_complexF', 'vcl_complex<float>'),
  ('vnl_vector', 'vnl_vector', 'vnl_vector_vcl_complexLD', 'vcl_complex<long double>'),
  ('vnl_unary_function', 'vnl_unary_function', 'vnl_unary_functionD_vnl_vectorD', 'double, vnl_vector< double >'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorD', 'double'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vector_vcl_complexD', 'vcl_complex<double>'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorF', 'float'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vector_vcl_complexF', 'vcl_complex<float>'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorSI', 'signed int'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorSL', 'signed long'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorLD', 'long double'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vector_vcl_complexLD', 'vcl_complex<long double>'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorSC', 'signed char'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorUC', 'unsigned char'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorUI', 'unsigned int'),
  ('vnl_c_vector', 'vnl_c_vector', 'vnl_c_vectorUL', 'unsigned long'),
  ('vnl_cost_function', 'vnl_cost_function', 'vnl_cost_function'),
  ('vnl_diag_matrix', 'vnl_diag_matrix', 'vnl_diag_matrixD', 'double'),
  ('vnl_diag_matrix', 'vnl_diag_matrix', 'vnl_diag_matrix_vcl_complexD', 'vcl_complex<double>'),
  ('vnl_diag_matrix', 'vnl_diag_matrix', 'vnl_diag_matrixF', 'float'),
  ('vnl_diag_matrix', 'vnl_diag_matrix', 'vnl_diag_matrix_vcl_complexF', 'vcl_complex<float>'),
  ('vnl_diag_matrix', 'vnl_diag_matrix', 'vnl_diag_matrixSI', 'signed int'),
  ('vnl_diag_matrix', 'vnl_diag_matrix', 'vnl_diag_matrixLD', 'long double'),
  ('vnl_file_matrix', 'vnl_file_matrix', 'vnl_file_matrixD', 'double'),
  ('vnl_file_matrix', 'vnl_file_matrix', 'vnl_file_matrixF', 'float'),
  ('vnl_file_vector', 'vnl_file_vector', 'vnl_file_vectorD', 'double'),
  ('vnl_fortran_copy', 'vnl_fortran_copy', 'vnl_fortran_copyD', 'double'),
  ('vnl_fortran_copy', 'vnl_fortran_copy', 'vnl_fortran_copy_vcl_complexD', 'vcl_complex<double>'),
  ('vnl_fortran_copy', 'vnl_fortran_copy', 'vnl_fortran_copyF', 'float'),
  ('vnl_fortran_copy', 'vnl_fortran_copy', 'vnl_fortran_copy_vcl_complexF', 'vcl_complex<float>'),
  ('vnl_least_squares_function', 'vnl_least_squares_function', 'vnl_least_squares_function'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_2_2', 'double,2,2'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_2_3', 'double,2,3'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_2_6', 'double,2,6'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_3_12', 'double,3,12'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_3_3', 'double,3,3'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_3_4', 'double,3,4'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_4_3', 'double,4,3'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedD_4_4', 'double,4,4'),
  ('vnl_matrix_fixed', 'vnl_matrix_fixed', 'vnl_matrix_fixedF_3_3', 'float,3,3'),
  ('vnl_matrix_fixed_ref_const', 'vnl_matrix_fixed_ref_const', 'vnl_matrix_fixed_ref_constF_3_3', 'float,3,3'),
  ('vnl_matrix_fixed_ref', 'vnl_matrix_fixed_ref', 'vnl_matrix_fixed_refF_3_3', 'float,3,3'),
  ('vnl_matrix_ref', 'vnl_matrix_ref', 'vnl_matrix_refD', 'double'),
  ('vnl_matrix_ref', 'vnl_matrix_ref', 'vnl_matrix_refF', 'float'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refD', 'double'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refF', 'float'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refSI', 'signed int'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refSL', 'signed long'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refLD', 'long double'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refSC', 'signed char'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refUC', 'unsigned char'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refUS', 'unsigned short'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refUI', 'unsigned int'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_refUL', 'unsigned long'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_ref_vcl_complexD', 'vcl_complex<double>'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_ref_vcl_complexF', 'vcl_complex<float>'),
  ('vnl_vector_ref', 'vnl_vector_ref', 'vnl_vector_ref_vcl_complexLD', 'vcl_complex<long double>'),
)
