# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info
if version_info >= (3,0,0):
    new_instancemethod = lambda func, inst, cls: _itkFFTComplexConjugateToRealImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkFFTComplexConjugateToRealImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkFFTComplexConjugateToRealImageFilterPython
            return _itkFFTComplexConjugateToRealImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkFFTComplexConjugateToRealImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkFFTComplexConjugateToRealImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkFFTComplexConjugateToRealImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import ITKCommonBasePython
import itkEventObjectsPython
import pyBasePython
import itkImageToImageFilterBPython
import ITKRegionsPython
import itkSizePython
import itkIndexPython
import itkOffsetPython
import itkImagePython
import itkFixedArrayPython
import itkCovariantVectorPython
import vnl_vectorPython
import vcl_complexPython
import vnl_matrixPython
import itkVectorPython
import vnl_vector_refPython
import itkPointPython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkRGBAPixelPython
import itkSymmetricSecondRankTensorPython
import itkRGBPixelPython
import itkImageSourcePython
import itkVectorImagePython
import itkVariableLengthVectorPython
def itkFFTComplexConjugateToRealImageFilterF3_New():
  return itkFFTComplexConjugateToRealImageFilterF3.New()

def itkFFTComplexConjugateToRealImageFilterF2_New():
  return itkFFTComplexConjugateToRealImageFilterF2.New()

class itkFFTComplexConjugateToRealImageFilterF2(itkImageToImageFilterBPython.itkImageToImageFilterICF2IF2):
    """Proxy of C++ itkFFTComplexConjugateToRealImageFilterF2 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    ImageDimension = _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_ImageDimension
    def __New_orig__():
        """__New_orig__()"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def GenerateOutputInformation(self):
        """GenerateOutputInformation(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_GenerateOutputInformation(self)

    def GenerateInputRequestedRegion(self):
        """GenerateInputRequestedRegion(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_GenerateInputRequestedRegion(self)

    def FullMatrix(self):
        """FullMatrix(self) -> bool"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_FullMatrix(self)

    def SetActualXDimensionIsOdd(self, *args):
        """SetActualXDimensionIsOdd(self, bool isodd)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_SetActualXDimensionIsOdd(self, *args)

    def SetActualXDimensionIsOddOn(self):
        """SetActualXDimensionIsOddOn(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_SetActualXDimensionIsOddOn(self)

    def SetActualXDimensionIsOddOff(self):
        """SetActualXDimensionIsOddOff(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_SetActualXDimensionIsOddOff(self)

    def ActualXDimensionIsOdd(self):
        """ActualXDimensionIsOdd(self) -> bool"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_ActualXDimensionIsOdd(self)

    __swig_destroy__ = _itkFFTComplexConjugateToRealImageFilterPython.delete_itkFFTComplexConjugateToRealImageFilterF2
    def cast(*args):
        """cast(itkLightObject obj) -> itkFFTComplexConjugateToRealImageFilterF2"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkFFTComplexConjugateToRealImageFilterF2"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkFFTComplexConjugateToRealImageFilterF2
        
        Create a new object of the class itkFFTComplexConjugateToRealImageFilterF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkFFTComplexConjugateToRealImageFilterF2.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkFFTComplexConjugateToRealImageFilterF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkFFTComplexConjugateToRealImageFilterF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkFFTComplexConjugateToRealImageFilterF2.GenerateOutputInformation = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_GenerateOutputInformation,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2.GenerateInputRequestedRegion = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_GenerateInputRequestedRegion,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2.FullMatrix = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_FullMatrix,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2.SetActualXDimensionIsOdd = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_SetActualXDimensionIsOdd,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2.SetActualXDimensionIsOddOn = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_SetActualXDimensionIsOddOn,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2.SetActualXDimensionIsOddOff = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_SetActualXDimensionIsOddOff,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2.ActualXDimensionIsOdd = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_ActualXDimensionIsOdd,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2.GetPointer = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_GetPointer,None,itkFFTComplexConjugateToRealImageFilterF2)
itkFFTComplexConjugateToRealImageFilterF2_swigregister = _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_swigregister
itkFFTComplexConjugateToRealImageFilterF2_swigregister(itkFFTComplexConjugateToRealImageFilterF2)

def itkFFTComplexConjugateToRealImageFilterF2___New_orig__():
  """itkFFTComplexConjugateToRealImageFilterF2___New_orig__()"""
  return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2___New_orig__()

def itkFFTComplexConjugateToRealImageFilterF2_cast(*args):
  """itkFFTComplexConjugateToRealImageFilterF2_cast(itkLightObject obj) -> itkFFTComplexConjugateToRealImageFilterF2"""
  return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF2_cast(*args)

class itkFFTComplexConjugateToRealImageFilterF3(itkImageToImageFilterBPython.itkImageToImageFilterICF3IF3):
    """Proxy of C++ itkFFTComplexConjugateToRealImageFilterF3 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    ImageDimension = _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_ImageDimension
    def __New_orig__():
        """__New_orig__()"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def GenerateOutputInformation(self):
        """GenerateOutputInformation(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_GenerateOutputInformation(self)

    def GenerateInputRequestedRegion(self):
        """GenerateInputRequestedRegion(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_GenerateInputRequestedRegion(self)

    def FullMatrix(self):
        """FullMatrix(self) -> bool"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_FullMatrix(self)

    def SetActualXDimensionIsOdd(self, *args):
        """SetActualXDimensionIsOdd(self, bool isodd)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_SetActualXDimensionIsOdd(self, *args)

    def SetActualXDimensionIsOddOn(self):
        """SetActualXDimensionIsOddOn(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_SetActualXDimensionIsOddOn(self)

    def SetActualXDimensionIsOddOff(self):
        """SetActualXDimensionIsOddOff(self)"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_SetActualXDimensionIsOddOff(self)

    def ActualXDimensionIsOdd(self):
        """ActualXDimensionIsOdd(self) -> bool"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_ActualXDimensionIsOdd(self)

    __swig_destroy__ = _itkFFTComplexConjugateToRealImageFilterPython.delete_itkFFTComplexConjugateToRealImageFilterF3
    def cast(*args):
        """cast(itkLightObject obj) -> itkFFTComplexConjugateToRealImageFilterF3"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkFFTComplexConjugateToRealImageFilterF3"""
        return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkFFTComplexConjugateToRealImageFilterF3
        
        Create a new object of the class itkFFTComplexConjugateToRealImageFilterF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkFFTComplexConjugateToRealImageFilterF3.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkFFTComplexConjugateToRealImageFilterF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkFFTComplexConjugateToRealImageFilterF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkFFTComplexConjugateToRealImageFilterF3.GenerateOutputInformation = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_GenerateOutputInformation,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3.GenerateInputRequestedRegion = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_GenerateInputRequestedRegion,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3.FullMatrix = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_FullMatrix,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3.SetActualXDimensionIsOdd = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_SetActualXDimensionIsOdd,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3.SetActualXDimensionIsOddOn = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_SetActualXDimensionIsOddOn,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3.SetActualXDimensionIsOddOff = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_SetActualXDimensionIsOddOff,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3.ActualXDimensionIsOdd = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_ActualXDimensionIsOdd,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3.GetPointer = new_instancemethod(_itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_GetPointer,None,itkFFTComplexConjugateToRealImageFilterF3)
itkFFTComplexConjugateToRealImageFilterF3_swigregister = _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_swigregister
itkFFTComplexConjugateToRealImageFilterF3_swigregister(itkFFTComplexConjugateToRealImageFilterF3)

def itkFFTComplexConjugateToRealImageFilterF3___New_orig__():
  """itkFFTComplexConjugateToRealImageFilterF3___New_orig__()"""
  return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3___New_orig__()

def itkFFTComplexConjugateToRealImageFilterF3_cast(*args):
  """itkFFTComplexConjugateToRealImageFilterF3_cast(itkLightObject obj) -> itkFFTComplexConjugateToRealImageFilterF3"""
  return _itkFFTComplexConjugateToRealImageFilterPython.itkFFTComplexConjugateToRealImageFilterF3_cast(*args)



