# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info
if version_info >= (3,0,0):
    new_instancemethod = lambda func, inst, cls: _itkMaximumImageFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkMaximumImageFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkMaximumImageFilterPython
            return _itkMaximumImageFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkMaximumImageFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkMaximumImageFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkMaximumImageFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import ITKCommonBasePython
import itkEventObjectsPython
import pyBasePython
import itkImagePython
import itkFixedArrayPython
import itkCovariantVectorPython
import vnl_vectorPython
import vcl_complexPython
import vnl_matrixPython
import itkVectorPython
import vnl_vector_refPython
import ITKRegionsPython
import itkSizePython
import itkIndexPython
import itkOffsetPython
import itkPointPython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkRGBAPixelPython
import itkSymmetricSecondRankTensorPython
import itkRGBPixelPython
import itkInPlaceImageFilterAPython
import itkImageToImageFilterBPython
import itkImageSourcePython
import itkVectorImagePython
import itkVariableLengthVectorPython
import itkImageToImageFilterAPython
def itkMaximumImageFilterID3ID3ID3_New():
  return itkMaximumImageFilterID3ID3ID3.New()

def itkMaximumImageFilterID3ID3ID3_Superclass_New():
  return itkMaximumImageFilterID3ID3ID3_Superclass.New()

def itkMaximumImageFilterID2ID2ID2_New():
  return itkMaximumImageFilterID2ID2ID2.New()

def itkMaximumImageFilterID2ID2ID2_Superclass_New():
  return itkMaximumImageFilterID2ID2ID2_Superclass.New()

def itkMaximumImageFilterIF3IF3IF3_New():
  return itkMaximumImageFilterIF3IF3IF3.New()

def itkMaximumImageFilterIF3IF3IF3_Superclass_New():
  return itkMaximumImageFilterIF3IF3IF3_Superclass.New()

def itkMaximumImageFilterIF2IF2IF2_New():
  return itkMaximumImageFilterIF2IF2IF2.New()

def itkMaximumImageFilterIF2IF2IF2_Superclass_New():
  return itkMaximumImageFilterIF2IF2IF2_Superclass.New()

def itkMaximumImageFilterIUS3IUS3IUS3_New():
  return itkMaximumImageFilterIUS3IUS3IUS3.New()

def itkMaximumImageFilterIUS3IUS3IUS3_Superclass_New():
  return itkMaximumImageFilterIUS3IUS3IUS3_Superclass.New()

def itkMaximumImageFilterIUS2IUS2IUS2_New():
  return itkMaximumImageFilterIUS2IUS2IUS2.New()

def itkMaximumImageFilterIUS2IUS2IUS2_Superclass_New():
  return itkMaximumImageFilterIUS2IUS2IUS2_Superclass.New()

def itkMaximumImageFilterIUL3IUL3IUL3_New():
  return itkMaximumImageFilterIUL3IUL3IUL3.New()

def itkMaximumImageFilterIUL3IUL3IUL3_Superclass_New():
  return itkMaximumImageFilterIUL3IUL3IUL3_Superclass.New()

def itkMaximumImageFilterIUL2IUL2IUL2_New():
  return itkMaximumImageFilterIUL2IUL2IUL2.New()

def itkMaximumImageFilterIUL2IUL2IUL2_Superclass_New():
  return itkMaximumImageFilterIUL2IUL2IUL2_Superclass.New()

def itkMaximumImageFilterIUC3IUC3IUC3_New():
  return itkMaximumImageFilterIUC3IUC3IUC3.New()

def itkMaximumImageFilterIUC3IUC3IUC3_Superclass_New():
  return itkMaximumImageFilterIUC3IUC3IUC3_Superclass.New()

def itkMaximumImageFilterIUC2IUC2IUC2_New():
  return itkMaximumImageFilterIUC2IUC2IUC2.New()

def itkMaximumImageFilterIUC2IUC2IUC2_Superclass_New():
  return itkMaximumImageFilterIUC2IUC2IUC2_Superclass.New()

class itkMaximumImageFilterID2ID2ID2_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterID2ID2):
    """Proxy of C++ itkMaximumImageFilterID2ID2ID2_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageD2 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageD2 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(double,double,double)>
        GetFunctor(self) -> itk::Function::Maximum<(double,double,double)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(double,double,double)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterID2ID2ID2_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterID2ID2ID2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterID2ID2ID2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterID2ID2ID2_Superclass
        
        Create a new object of the class itkMaximumImageFilterID2ID2ID2_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterID2ID2ID2_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterID2ID2ID2_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterID2ID2ID2_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterID2ID2ID2_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SetInput1,None,itkMaximumImageFilterID2ID2ID2_Superclass)
itkMaximumImageFilterID2ID2ID2_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SetInput2,None,itkMaximumImageFilterID2ID2ID2_Superclass)
itkMaximumImageFilterID2ID2ID2_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_GetFunctor,None,itkMaximumImageFilterID2ID2ID2_Superclass)
itkMaximumImageFilterID2ID2ID2_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_SetFunctor,None,itkMaximumImageFilterID2ID2ID2_Superclass)
itkMaximumImageFilterID2ID2ID2_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_GetPointer,None,itkMaximumImageFilterID2ID2ID2_Superclass)
itkMaximumImageFilterID2ID2ID2_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_swigregister
itkMaximumImageFilterID2ID2ID2_Superclass_swigregister(itkMaximumImageFilterID2ID2ID2_Superclass)

def itkMaximumImageFilterID2ID2ID2_Superclass___New_orig__():
  """itkMaximumImageFilterID2ID2ID2_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass___New_orig__()

def itkMaximumImageFilterID2ID2ID2_Superclass_cast(*args):
  """itkMaximumImageFilterID2ID2ID2_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterID2ID2ID2_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Superclass_cast(*args)

class itkMaximumImageFilterID3ID3ID3_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterID3ID3):
    """Proxy of C++ itkMaximumImageFilterID3ID3ID3_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageD3 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageD3 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(double,double,double)>
        GetFunctor(self) -> itk::Function::Maximum<(double,double,double)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(double,double,double)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterID3ID3ID3_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterID3ID3ID3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterID3ID3ID3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterID3ID3ID3_Superclass
        
        Create a new object of the class itkMaximumImageFilterID3ID3ID3_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterID3ID3ID3_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterID3ID3ID3_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterID3ID3ID3_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterID3ID3ID3_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SetInput1,None,itkMaximumImageFilterID3ID3ID3_Superclass)
itkMaximumImageFilterID3ID3ID3_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SetInput2,None,itkMaximumImageFilterID3ID3ID3_Superclass)
itkMaximumImageFilterID3ID3ID3_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_GetFunctor,None,itkMaximumImageFilterID3ID3ID3_Superclass)
itkMaximumImageFilterID3ID3ID3_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_SetFunctor,None,itkMaximumImageFilterID3ID3ID3_Superclass)
itkMaximumImageFilterID3ID3ID3_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_GetPointer,None,itkMaximumImageFilterID3ID3ID3_Superclass)
itkMaximumImageFilterID3ID3ID3_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_swigregister
itkMaximumImageFilterID3ID3ID3_Superclass_swigregister(itkMaximumImageFilterID3ID3ID3_Superclass)

def itkMaximumImageFilterID3ID3ID3_Superclass___New_orig__():
  """itkMaximumImageFilterID3ID3ID3_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass___New_orig__()

def itkMaximumImageFilterID3ID3ID3_Superclass_cast(*args):
  """itkMaximumImageFilterID3ID3ID3_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterID3ID3ID3_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Superclass_cast(*args)

class itkMaximumImageFilterIF2IF2IF2_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    """Proxy of C++ itkMaximumImageFilterIF2IF2IF2_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageF2 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageF2 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(float,float,float)>
        GetFunctor(self) -> itk::Function::Maximum<(float,float,float)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(float,float,float)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIF2IF2IF2_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIF2IF2IF2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIF2IF2IF2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIF2IF2IF2_Superclass
        
        Create a new object of the class itkMaximumImageFilterIF2IF2IF2_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIF2IF2IF2_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIF2IF2IF2_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIF2IF2IF2_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIF2IF2IF2_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SetInput1,None,itkMaximumImageFilterIF2IF2IF2_Superclass)
itkMaximumImageFilterIF2IF2IF2_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SetInput2,None,itkMaximumImageFilterIF2IF2IF2_Superclass)
itkMaximumImageFilterIF2IF2IF2_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_GetFunctor,None,itkMaximumImageFilterIF2IF2IF2_Superclass)
itkMaximumImageFilterIF2IF2IF2_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_SetFunctor,None,itkMaximumImageFilterIF2IF2IF2_Superclass)
itkMaximumImageFilterIF2IF2IF2_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_GetPointer,None,itkMaximumImageFilterIF2IF2IF2_Superclass)
itkMaximumImageFilterIF2IF2IF2_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_swigregister
itkMaximumImageFilterIF2IF2IF2_Superclass_swigregister(itkMaximumImageFilterIF2IF2IF2_Superclass)

def itkMaximumImageFilterIF2IF2IF2_Superclass___New_orig__():
  """itkMaximumImageFilterIF2IF2IF2_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass___New_orig__()

def itkMaximumImageFilterIF2IF2IF2_Superclass_cast(*args):
  """itkMaximumImageFilterIF2IF2IF2_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIF2IF2IF2_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Superclass_cast(*args)

class itkMaximumImageFilterIF3IF3IF3_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    """Proxy of C++ itkMaximumImageFilterIF3IF3IF3_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageF3 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageF3 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(float,float,float)>
        GetFunctor(self) -> itk::Function::Maximum<(float,float,float)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(float,float,float)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIF3IF3IF3_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIF3IF3IF3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIF3IF3IF3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIF3IF3IF3_Superclass
        
        Create a new object of the class itkMaximumImageFilterIF3IF3IF3_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIF3IF3IF3_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIF3IF3IF3_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIF3IF3IF3_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIF3IF3IF3_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SetInput1,None,itkMaximumImageFilterIF3IF3IF3_Superclass)
itkMaximumImageFilterIF3IF3IF3_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SetInput2,None,itkMaximumImageFilterIF3IF3IF3_Superclass)
itkMaximumImageFilterIF3IF3IF3_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_GetFunctor,None,itkMaximumImageFilterIF3IF3IF3_Superclass)
itkMaximumImageFilterIF3IF3IF3_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_SetFunctor,None,itkMaximumImageFilterIF3IF3IF3_Superclass)
itkMaximumImageFilterIF3IF3IF3_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_GetPointer,None,itkMaximumImageFilterIF3IF3IF3_Superclass)
itkMaximumImageFilterIF3IF3IF3_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_swigregister
itkMaximumImageFilterIF3IF3IF3_Superclass_swigregister(itkMaximumImageFilterIF3IF3IF3_Superclass)

def itkMaximumImageFilterIF3IF3IF3_Superclass___New_orig__():
  """itkMaximumImageFilterIF3IF3IF3_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass___New_orig__()

def itkMaximumImageFilterIF3IF3IF3_Superclass_cast(*args):
  """itkMaximumImageFilterIF3IF3IF3_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIF3IF3IF3_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Superclass_cast(*args)

class itkMaximumImageFilterIUC2IUC2IUC2_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC2IUC2):
    """Proxy of C++ itkMaximumImageFilterIUC2IUC2IUC2_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageUC2 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageUC2 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(unsigned char,unsigned char,unsigned char)>
        GetFunctor(self) -> itk::Function::Maximum<(unsigned char,unsigned char,unsigned char)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(unsigned char,unsigned char,unsigned char)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUC2IUC2IUC2_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUC2IUC2IUC2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUC2IUC2IUC2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUC2IUC2IUC2_Superclass
        
        Create a new object of the class itkMaximumImageFilterIUC2IUC2IUC2_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUC2IUC2IUC2_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUC2IUC2IUC2_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUC2IUC2IUC2_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUC2IUC2IUC2_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SetInput1,None,itkMaximumImageFilterIUC2IUC2IUC2_Superclass)
itkMaximumImageFilterIUC2IUC2IUC2_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SetInput2,None,itkMaximumImageFilterIUC2IUC2IUC2_Superclass)
itkMaximumImageFilterIUC2IUC2IUC2_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_GetFunctor,None,itkMaximumImageFilterIUC2IUC2IUC2_Superclass)
itkMaximumImageFilterIUC2IUC2IUC2_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_SetFunctor,None,itkMaximumImageFilterIUC2IUC2IUC2_Superclass)
itkMaximumImageFilterIUC2IUC2IUC2_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_GetPointer,None,itkMaximumImageFilterIUC2IUC2IUC2_Superclass)
itkMaximumImageFilterIUC2IUC2IUC2_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_swigregister
itkMaximumImageFilterIUC2IUC2IUC2_Superclass_swigregister(itkMaximumImageFilterIUC2IUC2IUC2_Superclass)

def itkMaximumImageFilterIUC2IUC2IUC2_Superclass___New_orig__():
  """itkMaximumImageFilterIUC2IUC2IUC2_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass___New_orig__()

def itkMaximumImageFilterIUC2IUC2IUC2_Superclass_cast(*args):
  """itkMaximumImageFilterIUC2IUC2IUC2_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIUC2IUC2IUC2_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Superclass_cast(*args)

class itkMaximumImageFilterIUC3IUC3IUC3_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUC3IUC3):
    """Proxy of C++ itkMaximumImageFilterIUC3IUC3IUC3_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageUC3 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageUC3 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(unsigned char,unsigned char,unsigned char)>
        GetFunctor(self) -> itk::Function::Maximum<(unsigned char,unsigned char,unsigned char)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(unsigned char,unsigned char,unsigned char)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUC3IUC3IUC3_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUC3IUC3IUC3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUC3IUC3IUC3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUC3IUC3IUC3_Superclass
        
        Create a new object of the class itkMaximumImageFilterIUC3IUC3IUC3_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUC3IUC3IUC3_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUC3IUC3IUC3_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUC3IUC3IUC3_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUC3IUC3IUC3_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SetInput1,None,itkMaximumImageFilterIUC3IUC3IUC3_Superclass)
itkMaximumImageFilterIUC3IUC3IUC3_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SetInput2,None,itkMaximumImageFilterIUC3IUC3IUC3_Superclass)
itkMaximumImageFilterIUC3IUC3IUC3_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_GetFunctor,None,itkMaximumImageFilterIUC3IUC3IUC3_Superclass)
itkMaximumImageFilterIUC3IUC3IUC3_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_SetFunctor,None,itkMaximumImageFilterIUC3IUC3IUC3_Superclass)
itkMaximumImageFilterIUC3IUC3IUC3_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_GetPointer,None,itkMaximumImageFilterIUC3IUC3IUC3_Superclass)
itkMaximumImageFilterIUC3IUC3IUC3_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_swigregister
itkMaximumImageFilterIUC3IUC3IUC3_Superclass_swigregister(itkMaximumImageFilterIUC3IUC3IUC3_Superclass)

def itkMaximumImageFilterIUC3IUC3IUC3_Superclass___New_orig__():
  """itkMaximumImageFilterIUC3IUC3IUC3_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass___New_orig__()

def itkMaximumImageFilterIUC3IUC3IUC3_Superclass_cast(*args):
  """itkMaximumImageFilterIUC3IUC3IUC3_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIUC3IUC3IUC3_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Superclass_cast(*args)

class itkMaximumImageFilterIUL2IUL2IUL2_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUL2IUL2):
    """Proxy of C++ itkMaximumImageFilterIUL2IUL2IUL2_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageUL2 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageUL2 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(unsigned long,unsigned long,unsigned long)>
        GetFunctor(self) -> itk::Function::Maximum<(unsigned long,unsigned long,unsigned long)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(unsigned long,unsigned long,unsigned long)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUL2IUL2IUL2_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUL2IUL2IUL2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUL2IUL2IUL2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUL2IUL2IUL2_Superclass
        
        Create a new object of the class itkMaximumImageFilterIUL2IUL2IUL2_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUL2IUL2IUL2_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUL2IUL2IUL2_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUL2IUL2IUL2_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUL2IUL2IUL2_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SetInput1,None,itkMaximumImageFilterIUL2IUL2IUL2_Superclass)
itkMaximumImageFilterIUL2IUL2IUL2_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SetInput2,None,itkMaximumImageFilterIUL2IUL2IUL2_Superclass)
itkMaximumImageFilterIUL2IUL2IUL2_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_GetFunctor,None,itkMaximumImageFilterIUL2IUL2IUL2_Superclass)
itkMaximumImageFilterIUL2IUL2IUL2_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_SetFunctor,None,itkMaximumImageFilterIUL2IUL2IUL2_Superclass)
itkMaximumImageFilterIUL2IUL2IUL2_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_GetPointer,None,itkMaximumImageFilterIUL2IUL2IUL2_Superclass)
itkMaximumImageFilterIUL2IUL2IUL2_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_swigregister
itkMaximumImageFilterIUL2IUL2IUL2_Superclass_swigregister(itkMaximumImageFilterIUL2IUL2IUL2_Superclass)

def itkMaximumImageFilterIUL2IUL2IUL2_Superclass___New_orig__():
  """itkMaximumImageFilterIUL2IUL2IUL2_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass___New_orig__()

def itkMaximumImageFilterIUL2IUL2IUL2_Superclass_cast(*args):
  """itkMaximumImageFilterIUL2IUL2IUL2_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIUL2IUL2IUL2_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Superclass_cast(*args)

class itkMaximumImageFilterIUL3IUL3IUL3_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUL3IUL3):
    """Proxy of C++ itkMaximumImageFilterIUL3IUL3IUL3_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageUL3 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageUL3 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(unsigned long,unsigned long,unsigned long)>
        GetFunctor(self) -> itk::Function::Maximum<(unsigned long,unsigned long,unsigned long)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(unsigned long,unsigned long,unsigned long)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUL3IUL3IUL3_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUL3IUL3IUL3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUL3IUL3IUL3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUL3IUL3IUL3_Superclass
        
        Create a new object of the class itkMaximumImageFilterIUL3IUL3IUL3_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUL3IUL3IUL3_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUL3IUL3IUL3_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUL3IUL3IUL3_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUL3IUL3IUL3_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SetInput1,None,itkMaximumImageFilterIUL3IUL3IUL3_Superclass)
itkMaximumImageFilterIUL3IUL3IUL3_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SetInput2,None,itkMaximumImageFilterIUL3IUL3IUL3_Superclass)
itkMaximumImageFilterIUL3IUL3IUL3_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_GetFunctor,None,itkMaximumImageFilterIUL3IUL3IUL3_Superclass)
itkMaximumImageFilterIUL3IUL3IUL3_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_SetFunctor,None,itkMaximumImageFilterIUL3IUL3IUL3_Superclass)
itkMaximumImageFilterIUL3IUL3IUL3_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_GetPointer,None,itkMaximumImageFilterIUL3IUL3IUL3_Superclass)
itkMaximumImageFilterIUL3IUL3IUL3_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_swigregister
itkMaximumImageFilterIUL3IUL3IUL3_Superclass_swigregister(itkMaximumImageFilterIUL3IUL3IUL3_Superclass)

def itkMaximumImageFilterIUL3IUL3IUL3_Superclass___New_orig__():
  """itkMaximumImageFilterIUL3IUL3IUL3_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass___New_orig__()

def itkMaximumImageFilterIUL3IUL3IUL3_Superclass_cast(*args):
  """itkMaximumImageFilterIUL3IUL3IUL3_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIUL3IUL3IUL3_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Superclass_cast(*args)

class itkMaximumImageFilterIUS2IUS2IUS2_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS2IUS2):
    """Proxy of C++ itkMaximumImageFilterIUS2IUS2IUS2_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageUS2 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageUS2 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(unsigned short,unsigned short,unsigned short)>
        GetFunctor(self) -> itk::Function::Maximum<(unsigned short,unsigned short,unsigned short)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(unsigned short,unsigned short,unsigned short)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUS2IUS2IUS2_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUS2IUS2IUS2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUS2IUS2IUS2_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUS2IUS2IUS2_Superclass
        
        Create a new object of the class itkMaximumImageFilterIUS2IUS2IUS2_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUS2IUS2IUS2_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUS2IUS2IUS2_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUS2IUS2IUS2_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUS2IUS2IUS2_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SetInput1,None,itkMaximumImageFilterIUS2IUS2IUS2_Superclass)
itkMaximumImageFilterIUS2IUS2IUS2_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SetInput2,None,itkMaximumImageFilterIUS2IUS2IUS2_Superclass)
itkMaximumImageFilterIUS2IUS2IUS2_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_GetFunctor,None,itkMaximumImageFilterIUS2IUS2IUS2_Superclass)
itkMaximumImageFilterIUS2IUS2IUS2_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_SetFunctor,None,itkMaximumImageFilterIUS2IUS2IUS2_Superclass)
itkMaximumImageFilterIUS2IUS2IUS2_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_GetPointer,None,itkMaximumImageFilterIUS2IUS2IUS2_Superclass)
itkMaximumImageFilterIUS2IUS2IUS2_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_swigregister
itkMaximumImageFilterIUS2IUS2IUS2_Superclass_swigregister(itkMaximumImageFilterIUS2IUS2IUS2_Superclass)

def itkMaximumImageFilterIUS2IUS2IUS2_Superclass___New_orig__():
  """itkMaximumImageFilterIUS2IUS2IUS2_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass___New_orig__()

def itkMaximumImageFilterIUS2IUS2IUS2_Superclass_cast(*args):
  """itkMaximumImageFilterIUS2IUS2IUS2_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIUS2IUS2IUS2_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Superclass_cast(*args)

class itkMaximumImageFilterIUS3IUS3IUS3_Superclass(itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS3IUS3):
    """Proxy of C++ itkMaximumImageFilterIUS3IUS3IUS3_Superclass class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    InputImage1Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_InputImage1Dimension
    InputImage2Dimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_InputImage2Dimension
    OutputImageDimension = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_OutputImageDimension
    SameDimensionCheck1 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SameDimensionCheck1
    SameDimensionCheck2 = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SameDimensionCheck2
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def SetInput1(self, *args):
        """SetInput1(self, itkImageUS3 image1)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SetInput1(self, *args)

    def SetInput2(self, *args):
        """SetInput2(self, itkImageUS3 image2)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SetInput2(self, *args)

    def GetFunctor(self, *args):
        """
        GetFunctor(self) -> itk::Function::Maximum<(unsigned short,unsigned short,unsigned short)>
        GetFunctor(self) -> itk::Function::Maximum<(unsigned short,unsigned short,unsigned short)>
        """
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_GetFunctor(self, *args)

    def SetFunctor(self, *args):
        """SetFunctor(self, itk::Function::Maximum<(unsigned short,unsigned short,unsigned short)> functor)"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SetFunctor(self, *args)

    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUS3IUS3IUS3_Superclass
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUS3IUS3IUS3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUS3IUS3IUS3_Superclass"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUS3IUS3IUS3_Superclass
        
        Create a new object of the class itkMaximumImageFilterIUS3IUS3IUS3_Superclass and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUS3IUS3IUS3_Superclass.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUS3IUS3IUS3_Superclass.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUS3IUS3IUS3_Superclass.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUS3IUS3IUS3_Superclass.SetInput1 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SetInput1,None,itkMaximumImageFilterIUS3IUS3IUS3_Superclass)
itkMaximumImageFilterIUS3IUS3IUS3_Superclass.SetInput2 = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SetInput2,None,itkMaximumImageFilterIUS3IUS3IUS3_Superclass)
itkMaximumImageFilterIUS3IUS3IUS3_Superclass.GetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_GetFunctor,None,itkMaximumImageFilterIUS3IUS3IUS3_Superclass)
itkMaximumImageFilterIUS3IUS3IUS3_Superclass.SetFunctor = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_SetFunctor,None,itkMaximumImageFilterIUS3IUS3IUS3_Superclass)
itkMaximumImageFilterIUS3IUS3IUS3_Superclass.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_GetPointer,None,itkMaximumImageFilterIUS3IUS3IUS3_Superclass)
itkMaximumImageFilterIUS3IUS3IUS3_Superclass_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_swigregister
itkMaximumImageFilterIUS3IUS3IUS3_Superclass_swigregister(itkMaximumImageFilterIUS3IUS3IUS3_Superclass)

def itkMaximumImageFilterIUS3IUS3IUS3_Superclass___New_orig__():
  """itkMaximumImageFilterIUS3IUS3IUS3_Superclass___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass___New_orig__()

def itkMaximumImageFilterIUS3IUS3IUS3_Superclass_cast(*args):
  """itkMaximumImageFilterIUS3IUS3IUS3_Superclass_cast(itkLightObject obj) -> itkMaximumImageFilterIUS3IUS3IUS3_Superclass"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Superclass_cast(*args)

class itkMaximumImageFilterID2ID2ID2(itkMaximumImageFilterID2ID2ID2_Superclass):
    """Proxy of C++ itkMaximumImageFilterID2ID2ID2 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterID2ID2ID2
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterID2ID2ID2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterID2ID2ID2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterID2ID2ID2
        
        Create a new object of the class itkMaximumImageFilterID2ID2ID2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterID2ID2ID2.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterID2ID2ID2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterID2ID2ID2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterID2ID2ID2.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_GetPointer,None,itkMaximumImageFilterID2ID2ID2)
itkMaximumImageFilterID2ID2ID2_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_swigregister
itkMaximumImageFilterID2ID2ID2_swigregister(itkMaximumImageFilterID2ID2ID2)

def itkMaximumImageFilterID2ID2ID2___New_orig__():
  """itkMaximumImageFilterID2ID2ID2___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2___New_orig__()

def itkMaximumImageFilterID2ID2ID2_cast(*args):
  """itkMaximumImageFilterID2ID2ID2_cast(itkLightObject obj) -> itkMaximumImageFilterID2ID2ID2"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID2ID2ID2_cast(*args)

class itkMaximumImageFilterID3ID3ID3(itkMaximumImageFilterID3ID3ID3_Superclass):
    """Proxy of C++ itkMaximumImageFilterID3ID3ID3 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterID3ID3ID3
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterID3ID3ID3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterID3ID3ID3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterID3ID3ID3
        
        Create a new object of the class itkMaximumImageFilterID3ID3ID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterID3ID3ID3.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterID3ID3ID3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterID3ID3ID3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterID3ID3ID3.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_GetPointer,None,itkMaximumImageFilterID3ID3ID3)
itkMaximumImageFilterID3ID3ID3_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_swigregister
itkMaximumImageFilterID3ID3ID3_swigregister(itkMaximumImageFilterID3ID3ID3)

def itkMaximumImageFilterID3ID3ID3___New_orig__():
  """itkMaximumImageFilterID3ID3ID3___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3___New_orig__()

def itkMaximumImageFilterID3ID3ID3_cast(*args):
  """itkMaximumImageFilterID3ID3ID3_cast(itkLightObject obj) -> itkMaximumImageFilterID3ID3ID3"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterID3ID3ID3_cast(*args)

class itkMaximumImageFilterIF2IF2IF2(itkMaximumImageFilterIF2IF2IF2_Superclass):
    """Proxy of C++ itkMaximumImageFilterIF2IF2IF2 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIF2IF2IF2
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIF2IF2IF2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIF2IF2IF2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIF2IF2IF2
        
        Create a new object of the class itkMaximumImageFilterIF2IF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIF2IF2IF2.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIF2IF2IF2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIF2IF2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIF2IF2IF2.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_GetPointer,None,itkMaximumImageFilterIF2IF2IF2)
itkMaximumImageFilterIF2IF2IF2_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_swigregister
itkMaximumImageFilterIF2IF2IF2_swigregister(itkMaximumImageFilterIF2IF2IF2)

def itkMaximumImageFilterIF2IF2IF2___New_orig__():
  """itkMaximumImageFilterIF2IF2IF2___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2___New_orig__()

def itkMaximumImageFilterIF2IF2IF2_cast(*args):
  """itkMaximumImageFilterIF2IF2IF2_cast(itkLightObject obj) -> itkMaximumImageFilterIF2IF2IF2"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF2IF2IF2_cast(*args)

class itkMaximumImageFilterIF3IF3IF3(itkMaximumImageFilterIF3IF3IF3_Superclass):
    """Proxy of C++ itkMaximumImageFilterIF3IF3IF3 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIF3IF3IF3
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIF3IF3IF3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIF3IF3IF3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIF3IF3IF3
        
        Create a new object of the class itkMaximumImageFilterIF3IF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIF3IF3IF3.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIF3IF3IF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIF3IF3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIF3IF3IF3.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_GetPointer,None,itkMaximumImageFilterIF3IF3IF3)
itkMaximumImageFilterIF3IF3IF3_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_swigregister
itkMaximumImageFilterIF3IF3IF3_swigregister(itkMaximumImageFilterIF3IF3IF3)

def itkMaximumImageFilterIF3IF3IF3___New_orig__():
  """itkMaximumImageFilterIF3IF3IF3___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3___New_orig__()

def itkMaximumImageFilterIF3IF3IF3_cast(*args):
  """itkMaximumImageFilterIF3IF3IF3_cast(itkLightObject obj) -> itkMaximumImageFilterIF3IF3IF3"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIF3IF3IF3_cast(*args)

class itkMaximumImageFilterIUC2IUC2IUC2(itkMaximumImageFilterIUC2IUC2IUC2_Superclass):
    """Proxy of C++ itkMaximumImageFilterIUC2IUC2IUC2 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUC2IUC2IUC2
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUC2IUC2IUC2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUC2IUC2IUC2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUC2IUC2IUC2
        
        Create a new object of the class itkMaximumImageFilterIUC2IUC2IUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUC2IUC2IUC2.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUC2IUC2IUC2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUC2IUC2IUC2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUC2IUC2IUC2.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_GetPointer,None,itkMaximumImageFilterIUC2IUC2IUC2)
itkMaximumImageFilterIUC2IUC2IUC2_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_swigregister
itkMaximumImageFilterIUC2IUC2IUC2_swigregister(itkMaximumImageFilterIUC2IUC2IUC2)

def itkMaximumImageFilterIUC2IUC2IUC2___New_orig__():
  """itkMaximumImageFilterIUC2IUC2IUC2___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2___New_orig__()

def itkMaximumImageFilterIUC2IUC2IUC2_cast(*args):
  """itkMaximumImageFilterIUC2IUC2IUC2_cast(itkLightObject obj) -> itkMaximumImageFilterIUC2IUC2IUC2"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC2IUC2IUC2_cast(*args)

class itkMaximumImageFilterIUC3IUC3IUC3(itkMaximumImageFilterIUC3IUC3IUC3_Superclass):
    """Proxy of C++ itkMaximumImageFilterIUC3IUC3IUC3 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUC3IUC3IUC3
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUC3IUC3IUC3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUC3IUC3IUC3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUC3IUC3IUC3
        
        Create a new object of the class itkMaximumImageFilterIUC3IUC3IUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUC3IUC3IUC3.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUC3IUC3IUC3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUC3IUC3IUC3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUC3IUC3IUC3.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_GetPointer,None,itkMaximumImageFilterIUC3IUC3IUC3)
itkMaximumImageFilterIUC3IUC3IUC3_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_swigregister
itkMaximumImageFilterIUC3IUC3IUC3_swigregister(itkMaximumImageFilterIUC3IUC3IUC3)

def itkMaximumImageFilterIUC3IUC3IUC3___New_orig__():
  """itkMaximumImageFilterIUC3IUC3IUC3___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3___New_orig__()

def itkMaximumImageFilterIUC3IUC3IUC3_cast(*args):
  """itkMaximumImageFilterIUC3IUC3IUC3_cast(itkLightObject obj) -> itkMaximumImageFilterIUC3IUC3IUC3"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUC3IUC3IUC3_cast(*args)

class itkMaximumImageFilterIUL2IUL2IUL2(itkMaximumImageFilterIUL2IUL2IUL2_Superclass):
    """Proxy of C++ itkMaximumImageFilterIUL2IUL2IUL2 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUL2IUL2IUL2
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUL2IUL2IUL2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUL2IUL2IUL2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUL2IUL2IUL2
        
        Create a new object of the class itkMaximumImageFilterIUL2IUL2IUL2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUL2IUL2IUL2.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUL2IUL2IUL2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUL2IUL2IUL2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUL2IUL2IUL2.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_GetPointer,None,itkMaximumImageFilterIUL2IUL2IUL2)
itkMaximumImageFilterIUL2IUL2IUL2_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_swigregister
itkMaximumImageFilterIUL2IUL2IUL2_swigregister(itkMaximumImageFilterIUL2IUL2IUL2)

def itkMaximumImageFilterIUL2IUL2IUL2___New_orig__():
  """itkMaximumImageFilterIUL2IUL2IUL2___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2___New_orig__()

def itkMaximumImageFilterIUL2IUL2IUL2_cast(*args):
  """itkMaximumImageFilterIUL2IUL2IUL2_cast(itkLightObject obj) -> itkMaximumImageFilterIUL2IUL2IUL2"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL2IUL2IUL2_cast(*args)

class itkMaximumImageFilterIUL3IUL3IUL3(itkMaximumImageFilterIUL3IUL3IUL3_Superclass):
    """Proxy of C++ itkMaximumImageFilterIUL3IUL3IUL3 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUL3IUL3IUL3
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUL3IUL3IUL3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUL3IUL3IUL3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUL3IUL3IUL3
        
        Create a new object of the class itkMaximumImageFilterIUL3IUL3IUL3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUL3IUL3IUL3.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUL3IUL3IUL3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUL3IUL3IUL3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUL3IUL3IUL3.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_GetPointer,None,itkMaximumImageFilterIUL3IUL3IUL3)
itkMaximumImageFilterIUL3IUL3IUL3_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_swigregister
itkMaximumImageFilterIUL3IUL3IUL3_swigregister(itkMaximumImageFilterIUL3IUL3IUL3)

def itkMaximumImageFilterIUL3IUL3IUL3___New_orig__():
  """itkMaximumImageFilterIUL3IUL3IUL3___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3___New_orig__()

def itkMaximumImageFilterIUL3IUL3IUL3_cast(*args):
  """itkMaximumImageFilterIUL3IUL3IUL3_cast(itkLightObject obj) -> itkMaximumImageFilterIUL3IUL3IUL3"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUL3IUL3IUL3_cast(*args)

class itkMaximumImageFilterIUS2IUS2IUS2(itkMaximumImageFilterIUS2IUS2IUS2_Superclass):
    """Proxy of C++ itkMaximumImageFilterIUS2IUS2IUS2 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUS2IUS2IUS2
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUS2IUS2IUS2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUS2IUS2IUS2"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUS2IUS2IUS2
        
        Create a new object of the class itkMaximumImageFilterIUS2IUS2IUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUS2IUS2IUS2.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUS2IUS2IUS2.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUS2IUS2IUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUS2IUS2IUS2.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_GetPointer,None,itkMaximumImageFilterIUS2IUS2IUS2)
itkMaximumImageFilterIUS2IUS2IUS2_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_swigregister
itkMaximumImageFilterIUS2IUS2IUS2_swigregister(itkMaximumImageFilterIUS2IUS2IUS2)

def itkMaximumImageFilterIUS2IUS2IUS2___New_orig__():
  """itkMaximumImageFilterIUS2IUS2IUS2___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2___New_orig__()

def itkMaximumImageFilterIUS2IUS2IUS2_cast(*args):
  """itkMaximumImageFilterIUS2IUS2IUS2_cast(itkLightObject obj) -> itkMaximumImageFilterIUS2IUS2IUS2"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS2IUS2IUS2_cast(*args)

class itkMaximumImageFilterIUS3IUS3IUS3(itkMaximumImageFilterIUS3IUS3IUS3_Superclass):
    """Proxy of C++ itkMaximumImageFilterIUS3IUS3IUS3 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    Input1ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Input1ConvertibleToOutputCheck
    Input2ConvertibleToOutputCheck = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Input2ConvertibleToOutputCheck
    Input1GreaterThanInput2Check = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_Input1GreaterThanInput2Check
    def __New_orig__():
        """__New_orig__()"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    __swig_destroy__ = _itkMaximumImageFilterPython.delete_itkMaximumImageFilterIUS3IUS3IUS3
    def cast(*args):
        """cast(itkLightObject obj) -> itkMaximumImageFilterIUS3IUS3IUS3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkMaximumImageFilterIUS3IUS3IUS3"""
        return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkMaximumImageFilterIUS3IUS3IUS3
        
        Create a new object of the class itkMaximumImageFilterIUS3IUS3IUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkMaximumImageFilterIUS3IUS3IUS3.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkMaximumImageFilterIUS3IUS3IUS3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkMaximumImageFilterIUS3IUS3IUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkMaximumImageFilterIUS3IUS3IUS3.GetPointer = new_instancemethod(_itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_GetPointer,None,itkMaximumImageFilterIUS3IUS3IUS3)
itkMaximumImageFilterIUS3IUS3IUS3_swigregister = _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_swigregister
itkMaximumImageFilterIUS3IUS3IUS3_swigregister(itkMaximumImageFilterIUS3IUS3IUS3)

def itkMaximumImageFilterIUS3IUS3IUS3___New_orig__():
  """itkMaximumImageFilterIUS3IUS3IUS3___New_orig__()"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3___New_orig__()

def itkMaximumImageFilterIUS3IUS3IUS3_cast(*args):
  """itkMaximumImageFilterIUS3IUS3IUS3_cast(itkLightObject obj) -> itkMaximumImageFilterIUS3IUS3IUS3"""
  return _itkMaximumImageFilterPython.itkMaximumImageFilterIUS3IUS3IUS3_cast(*args)



