%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkIsolatedWatershedImageFilterIUC2IUC2)

