%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodID3ID3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodID2ID2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIF3IF3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIF2IF2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionImageRegistrationMethodIUC2IUC2)

