%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkNarrowBandLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkNarrowBandLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkNarrowBandLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkNarrowBandLevelSetImageFilterIF2IF2F)

