%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorID3)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorID2)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIF3)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIF2)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIUS3)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIUS2)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIUL3)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIUL2)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIUC3)
DECLARE_REF_COUNT_CLASS(itkImageMomentsCalculatorIUC2)

