%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterID3ISSRTD33ID3)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIF3ISSRTD33IF3)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIUS3ISSRTD33IUS3)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIUL3ISSRTD33IUL3)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIUC3ISSRTD33IUC3)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterID2ISSRTD22ID2)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIF2ISSRTD22IF2)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIUS2ISSRTD22IUS2)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIUL2ISSRTD22IUL2)
DECLARE_REF_COUNT_CLASS(itkMultiScaleHessianBasedMeasureImageFilterIUC2ISSRTD22IUC2)

