%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterID3)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterID2)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIF3)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIF2)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkAdaptiveHistogramEqualizationImageFilterIUC2)

