%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkVectorThresholdSegmentationLevelSetImageFilterID3IVF33D)
DECLARE_REF_COUNT_CLASS(itkVectorThresholdSegmentationLevelSetImageFilterIF3IVF33F)
DECLARE_REF_COUNT_CLASS(itkVectorThresholdSegmentationLevelSetImageFilterID2IVF22D)
DECLARE_REF_COUNT_CLASS(itkVectorThresholdSegmentationLevelSetImageFilterIF2IVF22F)

