%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionID3ID3IVF33)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionID2ID2IVF22)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIF3IF3IVF33)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIF2IF2IVF22)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIUS3IUS3IVF33)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIUS2IUS2IVF22)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIUL3IUL3IVF33)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIUL2IUL2IVF22)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIUC3IUC3IVF33)
DECLARE_REF_COUNT_CLASS(itkPDEDeformableRegistrationFunctionIUC2IUC2IVF22)

