%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkBSplineUpsampleImageFilterIUC2IUC2)

