%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorB)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorSC)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorSS)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorSL)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorUC)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorUS)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorUL)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorF)
DECLARE_REF_COUNT_CLASS(itkSimpleDataObjectDecoratorD)

