%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicErodeImageFilterIUC2IUC2)

