%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBinaryShapeKeepNObjectsImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkBinaryShapeKeepNObjectsImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkBinaryShapeKeepNObjectsImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkBinaryShapeKeepNObjectsImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkBinaryShapeKeepNObjectsImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkBinaryShapeKeepNObjectsImageFilterIUC2)

