%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterID3ID3IVF33)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterID2ID2IVF22)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIF3IF3IVF33)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIF2IF2IVF22)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIUS3IUS3IVF33)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIUS2IUS2IVF22)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIUL3IUL3IVF33)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIUL2IUL2IVF22)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF33)
DECLARE_REF_COUNT_CLASS(itkFastSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF22)

