%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterID3)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterID2)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIF3)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIF2)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkPermuteAxesImageFilterIUC2)

