%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLaplacianSegmentationLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkLaplacianSegmentationLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkLaplacianSegmentationLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkLaplacianSegmentationLevelSetImageFilterIF2IF2F)

