%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterDDF3)
DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterDDF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterFFF3)
DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterFFF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterDDF2)
DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterDDF2_Superclass)
DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterFFF2)
DECLARE_REF_COUNT_CLASS(itkRealAndImaginaryToComplexImageFilterFFF2_Superclass)

