%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterID3F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIF3F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIUS3F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIUL3F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIUC3F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterID2F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIF2F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIUS2F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIUL2F)
DECLARE_REF_COUNT_CLASS(itkDifferenceOfGaussiansGradientImageFilterIUC2F)

