%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedClosingImageFilterIUC2IUC2)

