%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalOpeningImageFilterIUC2IUC2SE2)

