%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkOtsuMultipleThresholdsImageFilterIUC2IUC2)

