%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionID3D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIF3D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIUS3D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIUL3D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIUC3D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionID2D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIF2D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIUS2D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIUL2D)
DECLARE_REF_COUNT_CLASS(itkLinearInterpolateImageFunctionIUC2D)

