%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterID3ID3IVF33)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterID2ID2IVF22)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIF3IF3IVF33)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIF2IF2IVF22)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIUS3IUS3IVF33)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIUS2IUS2IVF22)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIUL3IUL3IVF33)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIUL2IUL2IVF22)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIUC3IUC3IVF33)
DECLARE_REF_COUNT_CLASS(itkDiffeomorphicDemonsRegistrationFilterIUC2IUC2IVF22)

