%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionID3ID3)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionID3ID3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionID3ID3_Superclass_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionID2ID2)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionID2ID2_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionID2ID2_Superclass_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionIF3IF3)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionIF3IF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionIF3IF3_Superclass_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionIF2IF2)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionIF2IF2_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseLevelSetFunctionIF2IF2_Superclass_Superclass)

