%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterID3)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterID2)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIF3)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIF2)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkChangeInformationImageFilterIUC2)

