%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkIsolatedConnectedImageFilterIUC2IUC2)

