%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalOpeningImageFilterIUC2IUC2SE2)

