%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterICVF33ICVF33)
DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterICVF22ICVF22)
DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterIVF33IVF33)
DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterIVF22IVF22)
DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkAnisotropicDiffusionImageFilterIF2IF2)

