%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM3ID3)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM3IF3)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM3IUS3)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM3IUL3)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM3IUC3)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM2ID2)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM2IF2)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM2IUS2)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM2IUL2)
DECLARE_REF_COUNT_CLASS(itkStatisticsLabelMapFilterLM2IUC2)

