%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkMultiResolutionPyramidImageFilterIUC2IUC2)

