%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterID3)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterID2)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIF3)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIF2)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkImageToVectorImageFilterIUC2)

