%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkCurvesLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkCurvesLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkCurvesLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkCurvesLevelSetImageFilterIF2IF2F)

