%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkHausdorffDistanceImageFilterIUC2IUC2)

