%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkMovingHistogramImageFilterBaseIUC2IUC2SE2)

