%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricID3ID3)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricID2ID2)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIF3IF3)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIF2IF2)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkMattesMutualInformationImageToImageMetricIUC2IUC2)

