%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkLaplacianSharpeningImageFilterIUC2IUC2)

