%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorID3)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorID2)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIF3)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIF2)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIUS3)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIUS2)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIUL3)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIUL2)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIUC3)
DECLARE_REF_COUNT_CLASS(itkPeakSignalToNoiseRatioCalculatorIUC2)

