%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorID3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorID2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIF3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIF2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIUS3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIUS2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIUL3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIUL2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIUC3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageCalculatorIUC2)

