%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkVectorCurvatureAnisotropicDiffusionImageFilterICVF33ICVF33)
DECLARE_REF_COUNT_CLASS(itkVectorCurvatureAnisotropicDiffusionImageFilterICVF22ICVF22)
DECLARE_REF_COUNT_CLASS(itkVectorCurvatureAnisotropicDiffusionImageFilterIVF33IVF33)
DECLARE_REF_COUNT_CLASS(itkVectorCurvatureAnisotropicDiffusionImageFilterIVF22IVF22)

