%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkComplexToImaginaryImageFilterICF3IF3)
DECLARE_REF_COUNT_CLASS(itkComplexToImaginaryImageFilterICF3IF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkComplexToImaginaryImageFilterICF2IF2)
DECLARE_REF_COUNT_CLASS(itkComplexToImaginaryImageFilterICF2IF2_Superclass)

