%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeRecursiveGaussianImageFilterIUC2IUC2)

