%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkSimilarityIndexImageFilterIUC2IUC2)

