%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD33ID3)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD33IF3)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD33IUS3)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD33IUL3)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD33IUC3)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD22ID2)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD22IF2)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD22IUS2)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD22IUL2)
DECLARE_REF_COUNT_CLASS(itkHessianToObjectnessMeasureImageFilterISSRTD22IUC2)

