%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkRecursiveSeparableImageFilterIUC2IUC2)

