%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkAnisotropicFourthOrderLevelSetImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkAnisotropicFourthOrderLevelSetImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkAnisotropicFourthOrderLevelSetImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkAnisotropicFourthOrderLevelSetImageFilterIF2IF2)

