%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkThresholdSegmentationLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkThresholdSegmentationLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkThresholdSegmentationLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkThresholdSegmentationLevelSetImageFilterIF2IF2F)

