%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkThresholdMaximumConnectedComponentsImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkThresholdMaximumConnectedComponentsImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkThresholdMaximumConnectedComponentsImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkThresholdMaximumConnectedComponentsImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkThresholdMaximumConnectedComponentsImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkThresholdMaximumConnectedComponentsImageFilterIUC2)

