%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterICVF33ICVF33)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterICVF22ICVF22)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterIVF33IVF33)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterIVF22IVF22)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceImageFilterIF2IF2)

