%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorID3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorID2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIF3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIF2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIUS3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIUS2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIUL3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIUL2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIUC3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToHistogramGeneratorIUC2)

