%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkFastMarchingUpwindGradientImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkFastMarchingUpwindGradientImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkFastMarchingUpwindGradientImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkFastMarchingUpwindGradientImageFilterIF2IF2)

