%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianImageFilterIUC2IUC2)

