%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkInterpolateImageFilterIUC2IUC2)

