%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkNarrowBandThresholdSegmentationLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkNarrowBandThresholdSegmentationLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkNarrowBandThresholdSegmentationLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkNarrowBandThresholdSegmentationLevelSetImageFilterIF2IF2F)

