%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkNeighborhoodConnectedImageFilterIUC2IUC2)

