%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterICVF33ICVF33)
DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterICVF22ICVF22)
DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterIVF33IVF33)
DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterIVF22IVF22)
DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkDenseFiniteDifferenceImageFilterIF2IF2)

