%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionID3DD)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIF3DF)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIUS3DUS)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIUL3DUL)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIUC3DUC)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionID2DD)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIF2DF)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIUS2DUS)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIUL2DUL)
DECLARE_REF_COUNT_CLASS(itkBSplineInterpolateImageFunctionIUC2DUC)

