%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBinaryImageToShapeLabelMapFilterIUS3LM3)
DECLARE_REF_COUNT_CLASS(itkBinaryImageToShapeLabelMapFilterIUS2LM2)
DECLARE_REF_COUNT_CLASS(itkBinaryImageToShapeLabelMapFilterIUL3LM3)
DECLARE_REF_COUNT_CLASS(itkBinaryImageToShapeLabelMapFilterIUL2LM2)
DECLARE_REF_COUNT_CLASS(itkBinaryImageToShapeLabelMapFilterIUC3LM3)
DECLARE_REF_COUNT_CLASS(itkBinaryImageToShapeLabelMapFilterIUC2LM2)

