%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkRecursiveMultiResolutionPyramidImageFilterIUC2IUC2)

