%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkOpeningByReconstructionImageFilterIUC2IUC2SE2)

