%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricID3ID3)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricID2ID2)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIF3IF3)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIF2IF2)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkMeanReciprocalSquareDifferenceImageToImageMetricIUC2IUC2)

