%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterID3ID3ID3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIF3IF3IF3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIUS3IUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIUL3IUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIUC3IUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterID2ID2ID2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIF2IF2IF2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIUS2IUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIUL2IUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageFilterIUC2IUC2IUC2)

