%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterID3)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterID2)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIF3)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIF2)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkHessianRecursiveGaussianImageFilterIUC2)

