%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkDirectedHausdorffDistanceImageFilterIUC2IUC2)

