%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterID3IVF33D)
DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterIF3IVF33F)
DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterID2IVF22D)
DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterIF2IVF22F)
DECLARE_REF_COUNT_CLASS(itkSegmentationLevelSetImageFilterIF2IF2F)

