%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkDynamicThresholdImageFilterIUC2IUC2)

