%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourLevelSetImageFilterIF2IF2F)

