%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkRegionOfInterestImageFilterIUC2IUC2)

