%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkDiscreteGaussianDerivativeImageFilterIUC2IUC2)

