%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkVotingBinaryHoleFillingImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryHoleFillingImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryHoleFillingImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryHoleFillingImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryHoleFillingImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryHoleFillingImageFilterIUC2IUC2)

