%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUS3IUS3_Superclass)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUS2IUS2_Superclass)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUL3IUL3_Superclass)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUL2IUL2_Superclass)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUC3IUC3_Superclass)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUC2IUC2)
DECLARE_REF_COUNT_CLASS(itkChangeLabelImageFilterIUC2IUC2_Superclass)

