%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkBinaryContourImageFilterIUC2IUC2)

