%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricID3ID3)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricID2ID2)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIF3IF3)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIF2IF2)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkMeanSquaresImageToImageMetricIUC2IUC2)

