%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFunctionDilateImageFilterIUC2IUC2SE2)

