%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkConvolutionImageFilterIUC2IUC2)

