%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkBSplineDecompositionImageFilterIUC2IUC2)

