%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorID3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorID2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIF3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIF2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIUS3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIUS2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIUL3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIUL2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIUC3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageCalculatorIUC2)

