%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUL3IUS3)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUL2IUS2)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUL3IUC3)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUL2IUC2)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkRelabelComponentImageFilterIUC2IUC2)

