%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkSaltAndPepperNoiseImageFilterIUC2IUC2)

