%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkZeroCrossingBasedEdgeDetectionImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkZeroCrossingBasedEdgeDetectionImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkZeroCrossingBasedEdgeDetectionImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkZeroCrossingBasedEdgeDetectionImageFilterIF2IF2)

