%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleFillholeImageFilterIUC2IUC2)

