%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionID3D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIF3D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIUS3D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIUL3D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIUC3D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionID2D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIF2D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIUS2D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIUL2D)
DECLARE_REF_COUNT_CLASS(itkBSplineResampleImageFunctionIUC2D)

