%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterID3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterID2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIF3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIF2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToTextureFeaturesFilterIUC2)

