%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkCenteredTransformInitializerVR3DTDID3ID3)
DECLARE_REF_COUNT_CLASS(itkCenteredTransformInitializerVR3DTDIF3IF3)
DECLARE_REF_COUNT_CLASS(itkCenteredTransformInitializerVR3DTDIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkCenteredTransformInitializerVR3DTDIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkCenteredTransformInitializerVR3DTDIUC3IUC3)

