%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGradientRecursiveGaussianImageFilterID2ICVF22)
DECLARE_REF_COUNT_CLASS(itkGradientRecursiveGaussianImageFilterIF2ICVF22)
DECLARE_REF_COUNT_CLASS(itkGradientRecursiveGaussianImageFilterIUS2ICVF22)
DECLARE_REF_COUNT_CLASS(itkGradientRecursiveGaussianImageFilterIUL2ICVF22)
DECLARE_REF_COUNT_CLASS(itkGradientRecursiveGaussianImageFilterIUC2ICVF22)

