%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodID3ID3)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodID2ID2)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIF3IF3)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIF2IF2)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkImageRegistrationMethodIUC2IUC2)

