%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkBinaryMorphologicalClosingImageFilterIUC2IUC2SE2)

