%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterID3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterID2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIF3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIF2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkMinimumMaximumImageFilterIUC2)

