%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUS3IUS3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUS2IUS2_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUL3IUL3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUL2IUL2_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUC3IUC3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUC2IUC2)
DECLARE_REF_COUNT_CLASS(itkScalarConnectedComponentImageFilterIUC2IUC2_Superclass)

