%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkContourMeanDistanceImageFilterIUC2IUC2)

