%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourShapePriorLevelSetImageFilterID3ID3D)
DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourShapePriorLevelSetImageFilterIF3IF3F)
DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourShapePriorLevelSetImageFilterID2ID2D)
DECLARE_REF_COUNT_CLASS(itkGeodesicActiveContourShapePriorLevelSetImageFilterIF2IF2F)

