%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionID3D)
DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionIF3F)
DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionID2D)
DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionIF2F)
DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionBaseID3D)
DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionBaseIF3F)
DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionBaseID2D)
DECLARE_REF_COUNT_CLASS(itkShapePriorMAPCostFunctionBaseIF2F)
DECLARE_REF_COUNT_CLASS(itkCumulativeGaussianCostFunction)
DECLARE_REF_COUNT_CLASS(itkMultipleValuedCostFunction)
DECLARE_REF_COUNT_CLASS(itkRandomVariateGeneratorBase)
DECLARE_REF_COUNT_CLASS(itkMultipleValuedCostFunction)
DECLARE_REF_COUNT_CLASS(itkSingleValuedCostFunction)
DECLARE_REF_COUNT_CLASS(itkCostFunction)

