%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIRGBUS3)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIRGBUS2)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterICVF33)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterICVF22)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIVF33)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIVF22)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterID3)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterID2)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIF3)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIF2)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkCheckerBoardImageFilterIUC2)

