%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionICVF33)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionICVF22)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIVF33)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIVF22)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionID3)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionID2)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIF3)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIF2)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIUS3)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIUS2)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIUL3)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIUL2)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIUC3)
DECLARE_REF_COUNT_CLASS(itkFiniteDifferenceFunctionIUC2)

