%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLabelShapeImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkLabelShapeImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkLabelShapeImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkLabelShapeImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkLabelShapeImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkLabelShapeImageFilterIUC2)

