%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkConnectedThresholdImageFilterIUC2IUC2)

