%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterID3ID3IVF33)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterID2ID2IVF22)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIF3IF3IVF33)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIF2IF2IVF22)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIUS3IUS3IVF33)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIUS2IUS2IVF22)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIUL3IUL3IVF33)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIUL2IUL2IVF22)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIUC3IUC3IVF33)
DECLARE_REF_COUNT_CLASS(itkSymmetricForcesDemonsRegistrationFilterIUC2IUC2IVF22)

