%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkNarrowBandImageFilterBaseID3ID3)
DECLARE_REF_COUNT_CLASS(itkNarrowBandImageFilterBaseID2ID2)
DECLARE_REF_COUNT_CLASS(itkNarrowBandImageFilterBaseIF3IF3)
DECLARE_REF_COUNT_CLASS(itkNarrowBandImageFilterBaseIF2IF2)

