%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkLaplacianRecursiveGaussianImageFilterIUC2IUC2)

