%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterID3ID3IVF33)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterID2ID2IVF22)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIF3IF3IVF33)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIF2IF2IVF22)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIUS3IUS3IVF33)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIUS2IUS2IVF22)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIUL3IUL3IVF33)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIUL2IUL2IVF22)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIUC3IUC3IVF33)
DECLARE_REF_COUNT_CLASS(itkLevelSetMotionRegistrationFilterIUC2IUC2IVF22)

