%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGeodesicDilateImageFilterIUC2IUC2)

