%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterID3ID3ID3)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterID3ID3ID3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterID3ID3ID3_Superclass_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterID2ID2ID2)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterID2ID2ID2_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterID2ID2ID2_Superclass_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterIF3IF3IF3)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterIF3IF3IF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterIF3IF3IF3_Superclass_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterIF2IF2IF2)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterIF2IF2IF2_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseDenseLevelSetImageFilterIF2IF2IF2_Superclass_Superclass)

