%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkVotingBinaryIterativeHoleFillingImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryIterativeHoleFillingImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryIterativeHoleFillingImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryIterativeHoleFillingImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryIterativeHoleFillingImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkVotingBinaryIterativeHoleFillingImageFilterIUC2)

