%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUS3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUS2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUS3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUS2IF2)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUL3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUL2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUL3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUL2IF2)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUC3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUC2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUC3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIUC2IF2)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedMaurerDistanceMapImageFilterIF2IF2)

