%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkVoronoiSegmentationImageFilterIUS2IUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkVoronoiSegmentationImageFilterIUS2IUS2IUS2_Superclass)
DECLARE_REF_COUNT_CLASS(itkVoronoiSegmentationImageFilterIUL2IUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkVoronoiSegmentationImageFilterIUL2IUL2IUL2_Superclass)
DECLARE_REF_COUNT_CLASS(itkVoronoiSegmentationImageFilterIUC2IUC2IUC2)
DECLARE_REF_COUNT_CLASS(itkVoronoiSegmentationImageFilterIUC2IUC2IUC2_Superclass)

