%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkSmoothingRecursiveGaussianImageFilterIUC2IUC2)

