%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkComplexToModulusImageFilterICF3IF3)
DECLARE_REF_COUNT_CLASS(itkComplexToModulusImageFilterICF3IF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkComplexToModulusImageFilterICF2IF2)
DECLARE_REF_COUNT_CLASS(itkComplexToModulusImageFilterICF2IF2_Superclass)

