%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricID3ID3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricID2ID2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIF3IF3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIF2IF2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkNormalizedCorrelationImageToImageMetricIUC2IUC2)

