%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUS3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUS2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUS3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUS2IF2)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUL3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUL2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUL3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUL2IF2)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUC3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUC2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUC3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIUC2IF2)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkSignedDanielssonDistanceMapImageFilterIF2IF2)

