%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkCollidingFrontsImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkCollidingFrontsImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkCollidingFrontsImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkCollidingFrontsImageFilterIF2IF2)

