%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLabelShapeKeepNObjectsImageFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkLabelShapeKeepNObjectsImageFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkLabelShapeKeepNObjectsImageFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkLabelShapeKeepNObjectsImageFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkLabelShapeKeepNObjectsImageFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkLabelShapeKeepNObjectsImageFilterIUC2)

