%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkContourDirectedMeanDistanceImageFilterIUC2IUC2)

