%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkRecursiveGaussianImageFilterIUC2IUC2)

