%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkAdditiveGaussianNoiseImageFilterIUC2IUC2)

