%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkLabelImageToShapeLabelMapFilterIUS3LM3)
DECLARE_REF_COUNT_CLASS(itkLabelImageToShapeLabelMapFilterIUS2LM2)
DECLARE_REF_COUNT_CLASS(itkLabelImageToShapeLabelMapFilterIUL3LM3)
DECLARE_REF_COUNT_CLASS(itkLabelImageToShapeLabelMapFilterIUL2LM2)
DECLARE_REF_COUNT_CLASS(itkLabelImageToShapeLabelMapFilterIUC3LM3)
DECLARE_REF_COUNT_CLASS(itkLabelImageToShapeLabelMapFilterIUC2LM2)

