%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF33ID3)
DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF33ID3_Superclass)
DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF22ID2)
DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF22ID2_Superclass)
DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF33IF3)
DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF33IF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF22IF2)
DECLARE_REF_COUNT_CLASS(itkEdgePotentialImageFilterICVF22IF2_Superclass)

