%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleGrindPeakImageFilterIUC2IUC2)

