%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkIsotropicFourthOrderLevelSetImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkIsotropicFourthOrderLevelSetImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkIsotropicFourthOrderLevelSetImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkIsotropicFourthOrderLevelSetImageFilterIF2IF2)

