%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSimpleMultipleContourExtractorImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkSimpleMultipleContourExtractorImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkSimpleMultipleContourExtractorImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkSimpleMultipleContourExtractorImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkSimpleMultipleContourExtractorImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkSimpleMultipleContourExtractorImageFilterIUC2IUC2)

