%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricID3ID3)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricID2ID2)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIF3IF3)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIF2IF2)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkMutualInformationImageToImageMetricIUC2IUC2)

