%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterDDF3)
DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterDDF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterFFF3)
DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterFFF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterDDF2)
DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterDDF2_Superclass)
DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterFFF2)
DECLARE_REF_COUNT_CLASS(itkMagnitudeAndPhaseToComplexImageFilterFFF2_Superclass)

