%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkMorphologicalGradientImageFilterIUC2IUC2SE2)

