%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleMorphologicalClosingImageFilterIUC2IUC2SE2)

