%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkOtsuThresholdImageFilterIUC2IUC2)

