%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkRegionalMinimaImageFilterIUC2IUC2)

