%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkBinaryThinningImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkBinaryThinningImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkBinaryThinningImageFilterIUC2IUC2)

