%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkErodeObjectMorphologyImageFilterIUC2IUC2SE2)

