%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO3ID3)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO3IF3)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO3IUS3)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO3IUL3)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO3IUC3)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO2ID2)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO2IF2)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO2IUS2)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO2IUL2)
DECLARE_REF_COUNT_CLASS(itkSpatialObjectToImageFilterSO2IUC2)

