%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkVectorGradientAnisotropicDiffusionImageFilterICVF33ICVF33)
DECLARE_REF_COUNT_CLASS(itkVectorGradientAnisotropicDiffusionImageFilterICVF22ICVF22)
DECLARE_REF_COUNT_CLASS(itkVectorGradientAnisotropicDiffusionImageFilterIVF33IVF33)
DECLARE_REF_COUNT_CLASS(itkVectorGradientAnisotropicDiffusionImageFilterIVF22IVF22)

