%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkRegionalMaximaImageFilterIUC2IUC2)

