%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGradientMagnitudeImageFilterIUC2IUC2)

