%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionID3D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIF3D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIUS3D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIUL3D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIUC3D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionID2D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIF2D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIUS2D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIUL2D)
DECLARE_REF_COUNT_CLASS(itkNearestNeighborInterpolateImageFunctionIUC2D)

