%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterID3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterID2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIF3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIF2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIUS3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIUS2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIUL3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIUL2)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIUC3)
DECLARE_REF_COUNT_CLASS(itkScalarImageToRunLengthMatrixFilterIUC2)

