%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkSimpleContourExtractorImageFilterIUC2IUC2)

