%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkGrayscaleConnectedOpeningImageFilterIUC2IUC2)

