%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIF2IF2)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIUS3IUS3)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIUS2IUS2)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIUL3IUL3)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIUL2IUL2)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIUC3IUC3)
DECLARE_REF_COUNT_CLASS(itkDynamicThreshold3DImageFilterIUC2IUC2)

