%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterID3ID3ID3)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterID3ID3ID3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterID2ID2ID2)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterID2ID2ID2_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterIF3IF3IF3)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterIF3IF3IF3_Superclass)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterIF2IF2IF2)
DECLARE_REF_COUNT_CLASS(itkScalarChanAndVeseSparseLevelSetImageFilterIF2IF2IF2_Superclass)

