%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterID3ID3SE3)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIF3IF3SE3)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIUS3IUS3SE3)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIUL3IUL3SE3)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIUC3IUC3SE3)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterID2ID2SE2)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIF2IF2SE2)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIUS2IUS2SE2)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIUL2IUL2SE2)
DECLARE_REF_COUNT_CLASS(itkClosingByReconstructionImageFilterIUC2IUC2SE2)

