%import wrap_pyBase.i

DECLARE_REF_COUNT_CLASS(itkApproximateSignedDistanceMapImageFilterID3ID3)
DECLARE_REF_COUNT_CLASS(itkApproximateSignedDistanceMapImageFilterID2ID2)
DECLARE_REF_COUNT_CLASS(itkApproximateSignedDistanceMapImageFilterIF3IF3)
DECLARE_REF_COUNT_CLASS(itkApproximateSignedDistanceMapImageFilterIF2IF2)

